// Code generated by mockery v2.3.0. DO NOT EDIT.

package config

import mock "github.com/stretchr/testify/mock"

// MockListener is an autogenerated mock type for the Listener type
type MockListener struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockListener) Execute(_a0 Config) {
	_m.Called(_a0)
}
