// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	model "duchatelle.io/dphoto/dphoto/backup/model"
	mock "github.com/stretchr/testify/mock"
)

// BackupReport is an autogenerated mock type for the BackupReport type
type BackupReport struct {
	mock.Mock
}

// CountPerAlbum provides a mock function with given fields:
func (_m *BackupReport) CountPerAlbum() map[string]*model.TypeCounter {
	ret := _m.Called()

	var r0 map[string]*model.TypeCounter
	if rf, ok := ret.Get(0).(func() map[string]*model.TypeCounter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*model.TypeCounter)
		}
	}

	return r0
}

// NewAlbums provides a mock function with given fields:
func (_m *BackupReport) NewAlbums() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Skipped provides a mock function with given fields:
func (_m *BackupReport) Skipped() model.MediaCounter {
	ret := _m.Called()

	var r0 model.MediaCounter
	if rf, ok := ret.Get(0).(func() model.MediaCounter); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.MediaCounter)
	}

	return r0
}

// WaitToComplete provides a mock function with given fields:
func (_m *BackupReport) WaitToComplete() {
	_m.Called()
}
