// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	io "io"

	model "duchatelle.io/dphoto/dphoto/backup/model"
	mock "github.com/stretchr/testify/mock"
)

// DetailsReaderAdapter is an autogenerated mock type for the DetailsReaderAdapter type
type DetailsReaderAdapter struct {
	mock.Mock
}

// ReadDetails provides a mock function with given fields: reader, options
func (_m *DetailsReaderAdapter) ReadDetails(reader io.Reader, options model.DetailsReaderOptions) (*model.MediaDetails, error) {
	ret := _m.Called(reader, options)

	var r0 *model.MediaDetails
	if rf, ok := ret.Get(0).(func(io.Reader, model.DetailsReaderOptions) *model.MediaDetails); ok {
		r0 = rf(reader, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MediaDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Reader, model.DetailsReaderOptions) error); ok {
		r1 = rf(reader, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
