// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	model "duchatelle.io/dphoto/dphoto/backup/model"
	mock "github.com/stretchr/testify/mock"
)

// DownloaderAdapter is an autogenerated mock type for the DownloaderAdapter type
type DownloaderAdapter struct {
	mock.Mock
}

// DownloadMedia provides a mock function with given fields: media
func (_m *DownloaderAdapter) DownloadMedia(media model.FoundMedia) (model.FoundMedia, error) {
	ret := _m.Called(media)

	var r0 model.FoundMedia
	if rf, ok := ret.Get(0).(func(model.FoundMedia) model.FoundMedia); ok {
		r0 = rf(media)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.FoundMedia)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.FoundMedia) error); ok {
		r1 = rf(media)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
