// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	backupmodel "duchatelle.io/dphoto/dphoto/backup/backupmodel"
	mock "github.com/stretchr/testify/mock"
)

// OnlineStorageAdapter is an autogenerated mock type for the OnlineStorageAdapter type
type OnlineStorageAdapter struct {
	mock.Mock
}

// MoveFile provides a mock function with given fields: folderName, filename, destFolderName
func (_m *OnlineStorageAdapter) MoveFile(folderName string, filename string, destFolderName string) (string, error) {
	ret := _m.Called(folderName, filename, destFolderName)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(folderName, filename, destFolderName)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(folderName, filename, destFolderName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFile provides a mock function with given fields: media, folderName, filename
func (_m *OnlineStorageAdapter) UploadFile(media backupmodel.ReadableMedia, folderName string, filename string) (string, error) {
	ret := _m.Called(media, folderName, filename)

	var r0 string
	if rf, ok := ret.Get(0).(func(backupmodel.ReadableMedia, string, string) string); ok {
		r0 = rf(media, folderName, filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(backupmodel.ReadableMedia, string, string) error); ok {
		r1 = rf(media, folderName, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
