// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	backupmodel "duchatelle.io/dphoto/dphoto/backup/backupmodel"
	mock "github.com/stretchr/testify/mock"
)

// PostAnalyseFilter is an autogenerated mock type for the PostAnalyseFilter type
type PostAnalyseFilter struct {
	mock.Mock
}

// AcceptAnalysedMedia provides a mock function with given fields: media, folderName
func (_m *PostAnalyseFilter) AcceptAnalysedMedia(media *backupmodel.AnalysedMedia, folderName string) bool {
	ret := _m.Called(media, folderName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*backupmodel.AnalysedMedia, string) bool); ok {
		r0 = rf(media, folderName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
