// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	ui "duchatelle.io/dphoto/dphoto/cmd/ui"
	mock "github.com/stretchr/testify/mock"
)

// RecordRepositoryPort is an autogenerated mock type for the RecordRepositoryPort type
type RecordRepositoryPort struct {
	mock.Mock
}

// FindRecords provides a mock function with given fields:
func (_m *RecordRepositoryPort) FindRecords() ([]*ui.Record, error) {
	ret := _m.Called()

	var r0 []*ui.Record
	if rf, ok := ret.Get(0).(func() []*ui.Record); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ui.Record)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
