// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	tracker "duchatelle.io/dphoto/dphoto/backup/interactors/tracker"
	mock "github.com/stretchr/testify/mock"
)

// TrackDownloaded is an autogenerated mock type for the TrackDownloaded type
type TrackDownloaded struct {
	mock.Mock
}

// OnDownloaded provides a mock function with given fields: done, total
func (_m *TrackDownloaded) OnDownloaded(done tracker.MediaCounter, total tracker.MediaCounter) {
	_m.Called(done, total)
}
