// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	model "duchatelle.io/dphoto/dphoto/backup/model"
	mock "github.com/stretchr/testify/mock"
)

// TrackScanComplete is an autogenerated mock type for the TrackScanComplete type
type TrackScanComplete struct {
	mock.Mock
}

// OnScanComplete provides a mock function with given fields: total
func (_m *TrackScanComplete) OnScanComplete(total model.MediaCounter) {
	_m.Called(total)
}
