// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	catalog "github.com/thomasduchatelle/dphoto/pkg/catalog"

	context "context"

	mock "github.com/stretchr/testify/mock"

	usermodel "github.com/thomasduchatelle/dphoto/pkg/usermodel"
)

// AlbumUnSharedObserver is an autogenerated mock type for the AlbumUnSharedObserver type
type AlbumUnSharedObserver struct {
	mock.Mock
}

type AlbumUnSharedObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *AlbumUnSharedObserver) EXPECT() *AlbumUnSharedObserver_Expecter {
	return &AlbumUnSharedObserver_Expecter{mock: &_m.Mock}
}

// AlbumUnShared provides a mock function with given fields: ctx, albumId, userEmail
func (_m *AlbumUnSharedObserver) AlbumUnShared(ctx context.Context, albumId catalog.AlbumId, userEmail usermodel.UserId) error {
	ret := _m.Called(ctx, albumId, userEmail)

	if len(ret) == 0 {
		panic("no return value specified for AlbumUnShared")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.AlbumId, usermodel.UserId) error); ok {
		r0 = rf(ctx, albumId, userEmail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumUnSharedObserver_AlbumUnShared_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AlbumUnShared'
type AlbumUnSharedObserver_AlbumUnShared_Call struct {
	*mock.Call
}

// AlbumUnShared is a helper method to define mock.On call
//   - ctx context.Context
//   - albumId catalog.AlbumId
//   - userEmail usermodel.UserId
func (_e *AlbumUnSharedObserver_Expecter) AlbumUnShared(ctx interface{}, albumId interface{}, userEmail interface{}) *AlbumUnSharedObserver_AlbumUnShared_Call {
	return &AlbumUnSharedObserver_AlbumUnShared_Call{Call: _e.mock.On("AlbumUnShared", ctx, albumId, userEmail)}
}

func (_c *AlbumUnSharedObserver_AlbumUnShared_Call) Run(run func(ctx context.Context, albumId catalog.AlbumId, userEmail usermodel.UserId)) *AlbumUnSharedObserver_AlbumUnShared_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.AlbumId), args[2].(usermodel.UserId))
	})
	return _c
}

func (_c *AlbumUnSharedObserver_AlbumUnShared_Call) Return(_a0 error) *AlbumUnSharedObserver_AlbumUnShared_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumUnSharedObserver_AlbumUnShared_Call) RunAndReturn(run func(context.Context, catalog.AlbumId, usermodel.UserId) error) *AlbumUnSharedObserver_AlbumUnShared_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlbumUnSharedObserver creates a new instance of AlbumUnSharedObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlbumUnSharedObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlbumUnSharedObserver {
	mock := &AlbumUnSharedObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
