// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/thomasduchatelle/dphoto/pkg/catalog"

	mock "github.com/stretchr/testify/mock"
)

// AlbumCanBeDeletedObserver is an autogenerated mock type for the AlbumCanBeDeletedObserver type
type AlbumCanBeDeletedObserver struct {
	mock.Mock
}

type AlbumCanBeDeletedObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *AlbumCanBeDeletedObserver) EXPECT() *AlbumCanBeDeletedObserver_Expecter {
	return &AlbumCanBeDeletedObserver_Expecter{mock: &_m.Mock}
}

// Observe provides a mock function with given fields: ctx, deletedAlbum, transfers
func (_m *AlbumCanBeDeletedObserver) Observe(ctx context.Context, deletedAlbum catalog.AlbumId, transfers catalog.MediaTransferRecords) error {
	ret := _m.Called(ctx, deletedAlbum, transfers)

	if len(ret) == 0 {
		panic("no return value specified for Observe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.AlbumId, catalog.MediaTransferRecords) error); ok {
		r0 = rf(ctx, deletedAlbum, transfers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AlbumCanBeDeletedObserver_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type AlbumCanBeDeletedObserver_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - ctx context.Context
//   - deletedAlbum catalog.AlbumId
//   - transfers catalog.MediaTransferRecords
func (_e *AlbumCanBeDeletedObserver_Expecter) Observe(ctx interface{}, deletedAlbum interface{}, transfers interface{}) *AlbumCanBeDeletedObserver_Observe_Call {
	return &AlbumCanBeDeletedObserver_Observe_Call{Call: _e.mock.On("Observe", ctx, deletedAlbum, transfers)}
}

func (_c *AlbumCanBeDeletedObserver_Observe_Call) Run(run func(ctx context.Context, deletedAlbum catalog.AlbumId, transfers catalog.MediaTransferRecords)) *AlbumCanBeDeletedObserver_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.AlbumId), args[2].(catalog.MediaTransferRecords))
	})
	return _c
}

func (_c *AlbumCanBeDeletedObserver_Observe_Call) Return(_a0 error) *AlbumCanBeDeletedObserver_Observe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlbumCanBeDeletedObserver_Observe_Call) RunAndReturn(run func(context.Context, catalog.AlbumId, catalog.MediaTransferRecords) error) *AlbumCanBeDeletedObserver_Observe_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlbumCanBeDeletedObserver creates a new instance of AlbumCanBeDeletedObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlbumCanBeDeletedObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlbumCanBeDeletedObserver {
	mock := &AlbumCanBeDeletedObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
