// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	backup "github.com/thomasduchatelle/dphoto/pkg/backup"

	mock "github.com/stretchr/testify/mock"
)

// Analyser is an autogenerated mock type for the Analyser type
type Analyser struct {
	mock.Mock
}

type Analyser_Expecter struct {
	mock *mock.Mock
}

func (_m *Analyser) EXPECT() *Analyser_Expecter {
	return &Analyser_Expecter{mock: &_m.Mock}
}

// Analyse provides a mock function with given fields: ctx, found, analysedMediaObserver
func (_m *Analyser) Analyse(ctx context.Context, found backup.FoundMedia, analysedMediaObserver backup.AnalysedMediaObserver, rejectsObserver backup.RejectedMediaObserver) error {
	ret := _m.Called(ctx, found, analysedMediaObserver)

	if len(ret) == 0 {
		panic("no return value specified for Analyse")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, backup.FoundMedia, backup.AnalysedMediaObserver) error); ok {
		r0 = rf(ctx, found, analysedMediaObserver)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Analyser_Analyse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analyse'
type Analyser_Analyse_Call struct {
	*mock.Call
}

// Analyse is a helper method to define mock.On call
//   - ctx context.Context
//   - found backup.FoundMedia
//   - analysedMediaObserver backup.AnalysedMediaObserver
func (_e *Analyser_Expecter) Analyse(ctx interface{}, found interface{}, analysedMediaObserver interface{}) *Analyser_Analyse_Call {
	return &Analyser_Analyse_Call{Call: _e.mock.On("Analyse", ctx, found, analysedMediaObserver)}
}

func (_c *Analyser_Analyse_Call) Run(run func(ctx context.Context, found backup.FoundMedia, analysedMediaObserver backup.AnalysedMediaObserver)) *Analyser_Analyse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(backup.FoundMedia), args[2].(backup.AnalysedMediaObserver))
	})
	return _c
}

func (_c *Analyser_Analyse_Call) Return(_a0 error) *Analyser_Analyse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Analyser_Analyse_Call) RunAndReturn(run func(context.Context, backup.FoundMedia, backup.AnalysedMediaObserver) error) *Analyser_Analyse_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnalyser creates a new instance of Analyser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyser(t interface {
	mock.TestingT
	Cleanup(func())
}) *Analyser {
	mock := &Analyser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
