// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	backup "github.com/thomasduchatelle/dphoto/pkg/backup"
)

// CatalogerFilterFunc is an autogenerated mock type for the CatalogerFilterFunc type
type CatalogerFilterFunc struct {
	mock.Mock
}

type CatalogerFilterFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *CatalogerFilterFunc) EXPECT() *CatalogerFilterFunc_Expecter {
	return &CatalogerFilterFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: media, reference
func (_m *CatalogerFilterFunc) Execute(media backup.AnalysedMedia, reference backup.CatalogReference) (backup.ProgressEventType, bool) {
	ret := _m.Called(media, reference)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 backup.ProgressEventType
	var r1 bool
	if rf, ok := ret.Get(0).(func(backup.AnalysedMedia, backup.CatalogReference) (backup.ProgressEventType, bool)); ok {
		return rf(media, reference)
	}
	if rf, ok := ret.Get(0).(func(backup.AnalysedMedia, backup.CatalogReference) backup.ProgressEventType); ok {
		r0 = rf(media, reference)
	} else {
		r0 = ret.Get(0).(backup.ProgressEventType)
	}

	if rf, ok := ret.Get(1).(func(backup.AnalysedMedia, backup.CatalogReference) bool); ok {
		r1 = rf(media, reference)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// CatalogerFilterFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type CatalogerFilterFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - media backup.AnalysedMedia
//   - reference backup.CatalogReference
func (_e *CatalogerFilterFunc_Expecter) Execute(media interface{}, reference interface{}) *CatalogerFilterFunc_Execute_Call {
	return &CatalogerFilterFunc_Execute_Call{Call: _e.mock.On("Execute", media, reference)}
}

func (_c *CatalogerFilterFunc_Execute_Call) Run(run func(media backup.AnalysedMedia, reference backup.CatalogReference)) *CatalogerFilterFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(backup.AnalysedMedia), args[1].(backup.CatalogReference))
	})
	return _c
}

func (_c *CatalogerFilterFunc_Execute_Call) Return(_a0 backup.ProgressEventType, _a1 bool) *CatalogerFilterFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CatalogerFilterFunc_Execute_Call) RunAndReturn(run func(backup.AnalysedMedia, backup.CatalogReference) (backup.ProgressEventType, bool)) *CatalogerFilterFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewCatalogerFilterFunc creates a new instance of CatalogerFilterFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogerFilterFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *CatalogerFilterFunc {
	mock := &CatalogerFilterFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
