// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dnsdomain "github.com/thomasduchatelle/dphoto/pkg/dnsdomain"
)

// CertificateManager is an autogenerated mock type for the CertificateManager type
type CertificateManager struct {
	mock.Mock
}

// FindCertificate provides a mock function with given fields: ctx, domain
func (_m *CertificateManager) FindCertificate(ctx context.Context, domain string) (*dnsdomain.ExistingCertificate, error) {
	ret := _m.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for FindCertificate")
	}

	var r0 *dnsdomain.ExistingCertificate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dnsdomain.ExistingCertificate, error)); ok {
		return rf(ctx, domain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dnsdomain.ExistingCertificate); ok {
		r0 = rf(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dnsdomain.ExistingCertificate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InstallCertificate provides a mock function with given fields: ctx, id, certificate
func (_m *CertificateManager) InstallCertificate(ctx context.Context, id string, certificate dnsdomain.CompleteCertificate) error {
	ret := _m.Called(ctx, id, certificate)

	if len(ret) == 0 {
		panic("no return value specified for InstallCertificate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dnsdomain.CompleteCertificate) error); ok {
		r0 = rf(ctx, id, certificate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCertificateManager creates a new instance of CertificateManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertificateManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertificateManager {
	mock := &CertificateManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
