// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	aws "github.com/aws/aws-sdk-go-v2/aws"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ConfigFactoryFunc is an autogenerated mock type for the ConfigFactoryFunc type
type ConfigFactoryFunc struct {
	mock.Mock
}

type ConfigFactoryFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigFactoryFunc) EXPECT() *ConfigFactoryFunc_Expecter {
	return &ConfigFactoryFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *ConfigFactoryFunc) Execute(ctx context.Context) (aws.Config, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 aws.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (aws.Config, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) aws.Config); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(aws.Config)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigFactoryFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ConfigFactoryFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ConfigFactoryFunc_Expecter) Execute(ctx interface{}) *ConfigFactoryFunc_Execute_Call {
	return &ConfigFactoryFunc_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *ConfigFactoryFunc_Execute_Call) Run(run func(ctx context.Context)) *ConfigFactoryFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ConfigFactoryFunc_Execute_Call) Return(_a0 aws.Config, _a1 error) *ConfigFactoryFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConfigFactoryFunc_Execute_Call) RunAndReturn(run func(context.Context) (aws.Config, error)) *ConfigFactoryFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewConfigFactoryFunc creates a new instance of ConfigFactoryFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigFactoryFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigFactoryFunc {
	mock := &ConfigFactoryFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
