// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/thomasduchatelle/dphoto/pkg/catalog"

	mock "github.com/stretchr/testify/mock"
)

// CreateAlbumObserver is an autogenerated mock type for the CreateAlbumObserver type
type CreateAlbumObserver struct {
	mock.Mock
}

type CreateAlbumObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *CreateAlbumObserver) EXPECT() *CreateAlbumObserver_Expecter {
	return &CreateAlbumObserver_Expecter{mock: &_m.Mock}
}

// ObserveCreateAlbum provides a mock function with given fields: ctx, album
func (_m *CreateAlbumObserver) ObserveCreateAlbum(ctx context.Context, createdAlbum catalog.Album, existingAlbums []catalog.Album) error {
	ret := _m.Called(ctx, createdAlbum)

	if len(ret) == 0 {
		panic("no return value specified for ObserveCreateAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Album) error); ok {
		r0 = rf(ctx, createdAlbum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAlbumObserver_ObserveCreateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveCreateAlbum'
type CreateAlbumObserver_ObserveCreateAlbum_Call struct {
	*mock.Call
}

// ObserveCreateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - album catalog.Album
func (_e *CreateAlbumObserver_Expecter) ObserveCreateAlbum(ctx interface{}, album interface{}) *CreateAlbumObserver_ObserveCreateAlbum_Call {
	return &CreateAlbumObserver_ObserveCreateAlbum_Call{Call: _e.mock.On("ObserveCreateAlbum", ctx, album)}
}

func (_c *CreateAlbumObserver_ObserveCreateAlbum_Call) Run(run func(ctx context.Context, album catalog.Album)) *CreateAlbumObserver_ObserveCreateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.Album))
	})
	return _c
}

func (_c *CreateAlbumObserver_ObserveCreateAlbum_Call) Return(_a0 error) *CreateAlbumObserver_ObserveCreateAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CreateAlbumObserver_ObserveCreateAlbum_Call) RunAndReturn(run func(context.Context, catalog.Album) error) *CreateAlbumObserver_ObserveCreateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewCreateAlbumObserver creates a new instance of CreateAlbumObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateAlbumObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateAlbumObserver {
	mock := &CreateAlbumObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
