// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/thomasduchatelle/dphoto/pkg/catalog"

	mock "github.com/stretchr/testify/mock"
)

// DeleteAlbumRepositoryFunc is an autogenerated mock type for the DeleteAlbumRepositoryFunc type
type DeleteAlbumRepositoryFunc struct {
	mock.Mock
}

type DeleteAlbumRepositoryFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *DeleteAlbumRepositoryFunc) EXPECT() *DeleteAlbumRepositoryFunc_Expecter {
	return &DeleteAlbumRepositoryFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, redirectTo
func (_m *DeleteAlbumRepositoryFunc) Execute(ctx context.Context, albumId catalog.AlbumId) error {
	ret := _m.Called(ctx, albumId)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.AlbumId) error); ok {
		r0 = rf(ctx, albumId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAlbumRepositoryFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type DeleteAlbumRepositoryFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - redirectTo catalog.AlbumId
func (_e *DeleteAlbumRepositoryFunc_Expecter) Execute(ctx interface{}, albumId interface{}) *DeleteAlbumRepositoryFunc_Execute_Call {
	return &DeleteAlbumRepositoryFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, albumId)}
}

func (_c *DeleteAlbumRepositoryFunc_Execute_Call) Run(run func(ctx context.Context, albumId catalog.AlbumId)) *DeleteAlbumRepositoryFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.AlbumId))
	})
	return _c
}

func (_c *DeleteAlbumRepositoryFunc_Execute_Call) Return(_a0 error) *DeleteAlbumRepositoryFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeleteAlbumRepositoryFunc_Execute_Call) RunAndReturn(run func(context.Context, catalog.AlbumId) error) *DeleteAlbumRepositoryFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeleteAlbumRepositoryFunc creates a new instance of DeleteAlbumRepositoryFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteAlbumRepositoryFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteAlbumRepositoryFunc {
	mock := &DeleteAlbumRepositoryFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
