// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"

	mock "github.com/stretchr/testify/mock"
)

// DynamoQuery is an autogenerated mock type for the DynamoQuery type
type DynamoQuery struct {
	mock.Mock
}

type DynamoQuery_Expecter struct {
	mock *mock.Mock
}

func (_m *DynamoQuery) EXPECT() *DynamoQuery_Expecter {
	return &DynamoQuery_Expecter{mock: &_m.Mock}
}

// Query provides a mock function with given fields: ctx, d, optFns
func (_m *DynamoQuery) Query(ctx context.Context, d *dynamodb.QueryInput, optFns ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, d)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *dynamodb.QueryOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error)); ok {
		return rf(ctx, d, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) *dynamodb.QueryOutput); ok {
		r0 = rf(ctx, d, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.QueryOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) error); ok {
		r1 = rf(ctx, d, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DynamoQuery_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type DynamoQuery_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - d *dynamodb.QueryInput
//   - optFns ...func(*dynamodb.Options)
func (_e *DynamoQuery_Expecter) Query(ctx interface{}, d interface{}, optFns ...interface{}) *DynamoQuery_Query_Call {
	return &DynamoQuery_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, d}, optFns...)...)}
}

func (_c *DynamoQuery_Query_Call) Run(run func(ctx context.Context, d *dynamodb.QueryInput, optFns ...func(*dynamodb.Options))) *DynamoQuery_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*dynamodb.QueryInput), variadicArgs...)
	})
	return _c
}

func (_c *DynamoQuery_Query_Call) Return(_a0 *dynamodb.QueryOutput, _a1 error) *DynamoQuery_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DynamoQuery_Query_Call) RunAndReturn(run func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error)) *DynamoQuery_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewDynamoQuery creates a new instance of DynamoQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamoQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *DynamoQuery {
	mock := &DynamoQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
