// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/thomasduchatelle/dphoto/pkg/catalog"

	mock "github.com/stretchr/testify/mock"
)

// FindAlbumsByOwnerPortFunc is an autogenerated mock type for the FindAlbumsByOwnerPortFunc type
type FindAlbumsByOwnerPortFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, owner
func (_m *FindAlbumsByOwnerPortFunc) Execute(ctx context.Context, owner catalog.Owner) ([]*catalog.Album, error) {
	ret := _m.Called(ctx, owner)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*catalog.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Owner) ([]*catalog.Album, error)); ok {
		return rf(ctx, owner)
	}
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Owner) []*catalog.Album); ok {
		r0 = rf(ctx, owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*catalog.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, catalog.Owner) error); ok {
		r1 = rf(ctx, owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFindAlbumsByOwnerPortFunc creates a new instance of FindAlbumsByOwnerPortFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFindAlbumsByOwnerPortFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *FindAlbumsByOwnerPortFunc {
	mock := &FindAlbumsByOwnerPortFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
