// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	catalog "github.com/thomasduchatelle/dphoto/pkg/catalog"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// FindAlbumsByIdsPort is an autogenerated mock type for the FindAlbumsByIdsPort type
type FindAlbumsByIdsPort struct {
	mock.Mock
}

type FindAlbumsByIdsPort_Expecter struct {
	mock *mock.Mock
}

func (_m *FindAlbumsByIdsPort) EXPECT() *FindAlbumsByIdsPort_Expecter {
	return &FindAlbumsByIdsPort_Expecter{mock: &_m.Mock}
}

// FindAlbumsById provides a mock function with given fields: ctx, ids
func (_m *FindAlbumsByIdsPort) FindAlbumsById(ctx context.Context, ids []catalog.AlbumId) ([]*catalog.Album, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FindAlbumsById")
	}

	var r0 []*catalog.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []catalog.AlbumId) ([]*catalog.Album, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []catalog.AlbumId) []*catalog.Album); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*catalog.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []catalog.AlbumId) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAlbumsByIdsPort_FindAlbumsById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAlbumsById'
type FindAlbumsByIdsPort_FindAlbumsById_Call struct {
	*mock.Call
}

// FindAlbumsById is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []catalog.AlbumId
func (_e *FindAlbumsByIdsPort_Expecter) FindAlbumsById(ctx interface{}, ids interface{}) *FindAlbumsByIdsPort_FindAlbumsById_Call {
	return &FindAlbumsByIdsPort_FindAlbumsById_Call{Call: _e.mock.On("FindAlbumsById", ctx, ids)}
}

func (_c *FindAlbumsByIdsPort_FindAlbumsById_Call) Run(run func(ctx context.Context, ids []catalog.AlbumId)) *FindAlbumsByIdsPort_FindAlbumsById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]catalog.AlbumId))
	})
	return _c
}

func (_c *FindAlbumsByIdsPort_FindAlbumsById_Call) Return(_a0 []*catalog.Album, _a1 error) *FindAlbumsByIdsPort_FindAlbumsById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FindAlbumsByIdsPort_FindAlbumsById_Call) RunAndReturn(run func(context.Context, []catalog.AlbumId) ([]*catalog.Album, error)) *FindAlbumsByIdsPort_FindAlbumsById_Call {
	_c.Call.Return(run)
	return _c
}

// NewFindAlbumsByIdsPort creates a new instance of FindAlbumsByIdsPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFindAlbumsByIdsPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *FindAlbumsByIdsPort {
	mock := &FindAlbumsByIdsPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
