// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	dynamodb "github.com/aws/aws-sdk-go/service/dynamodb"

	mock "github.com/stretchr/testify/mock"
)

// GetStreamAdapter is an autogenerated mock type for the GetStreamAdapter type
type GetStreamAdapter struct {
	mock.Mock
}

// BatchGet provides a mock function with given fields: _a0
func (_m *GetStreamAdapter) BatchGet(_a0 []map[string]*dynamodb.AttributeValue) (*dynamodb.BatchGetItemOutput, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for BatchGet")
	}

	var r0 *dynamodb.BatchGetItemOutput
	var r1 error
	if rf, ok := ret.Get(0).(func([]map[string]*dynamodb.AttributeValue) (*dynamodb.BatchGetItemOutput, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]map[string]*dynamodb.AttributeValue) *dynamodb.BatchGetItemOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.BatchGetItemOutput)
		}
	}

	if rf, ok := ret.Get(1).(func([]map[string]*dynamodb.AttributeValue) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetStreamAdapter creates a new instance of GetStreamAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetStreamAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetStreamAdapter {
	mock := &GetStreamAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
