// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dynamodb "github.com/aws/aws-sdk-go-v2/service/dynamodb"

	mock "github.com/stretchr/testify/mock"

	types "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

// GetStreamAdapter is an autogenerated mock type for the GetStreamAdapter type
type GetStreamAdapter struct {
	mock.Mock
}

// BatchGet provides a mock function with given fields: ctx, key
func (_m *GetStreamAdapter) BatchGet(ctx context.Context, key []map[string]types.AttributeValue) (*dynamodb.BatchGetItemOutput, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for BatchGet")
	}

	var r0 *dynamodb.BatchGetItemOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []map[string]types.AttributeValue) (*dynamodb.BatchGetItemOutput, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []map[string]types.AttributeValue) *dynamodb.BatchGetItemOutput); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.BatchGetItemOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []map[string]types.AttributeValue) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetStreamAdapter creates a new instance of GetStreamAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetStreamAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetStreamAdapter {
	mock := &GetStreamAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
