// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	aclcore "github.com/thomasduchatelle/dphoto/pkg/acl/aclcore"

	mock "github.com/stretchr/testify/mock"

	usermodel "github.com/thomasduchatelle/dphoto/pkg/usermodel"
)

// IdentityRepository is an autogenerated mock type for the IdentityRepository type
type IdentityRepository struct {
	mock.Mock
}

type IdentityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IdentityRepository) EXPECT() *IdentityRepository_Expecter {
	return &IdentityRepository_Expecter{mock: &_m.Mock}
}

// FindIdentities provides a mock function with given fields: emails
func (_m *IdentityRepository) FindIdentities(emails []usermodel.UserId) ([]*aclcore.Identity, error) {
	ret := _m.Called(emails)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentities")
	}

	var r0 []*aclcore.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func([]usermodel.UserId) ([]*aclcore.Identity, error)); ok {
		return rf(emails)
	}
	if rf, ok := ret.Get(0).(func([]usermodel.UserId) []*aclcore.Identity); ok {
		r0 = rf(emails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aclcore.Identity)
		}
	}

	if rf, ok := ret.Get(1).(func([]usermodel.UserId) error); ok {
		r1 = rf(emails)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityRepository_FindIdentities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdentities'
type IdentityRepository_FindIdentities_Call struct {
	*mock.Call
}

// FindIdentities is a helper method to define mock.On call
//   - emails []usermodel.UserId
func (_e *IdentityRepository_Expecter) FindIdentities(emails interface{}) *IdentityRepository_FindIdentities_Call {
	return &IdentityRepository_FindIdentities_Call{Call: _e.mock.On("FindIdentities", emails)}
}

func (_c *IdentityRepository_FindIdentities_Call) Run(run func(emails []usermodel.UserId)) *IdentityRepository_FindIdentities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]usermodel.UserId))
	})
	return _c
}

func (_c *IdentityRepository_FindIdentities_Call) Return(_a0 []*aclcore.Identity, _a1 error) *IdentityRepository_FindIdentities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityRepository_FindIdentities_Call) RunAndReturn(run func([]usermodel.UserId) ([]*aclcore.Identity, error)) *IdentityRepository_FindIdentities_Call {
	_c.Call.Return(run)
	return _c
}

// FindIdentity provides a mock function with given fields: email
func (_m *IdentityRepository) FindIdentity(email usermodel.UserId) (*aclcore.Identity, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentity")
	}

	var r0 *aclcore.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func(usermodel.UserId) (*aclcore.Identity, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(usermodel.UserId) *aclcore.Identity); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aclcore.Identity)
		}
	}

	if rf, ok := ret.Get(1).(func(usermodel.UserId) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IdentityRepository_FindIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindIdentity'
type IdentityRepository_FindIdentity_Call struct {
	*mock.Call
}

// FindIdentity is a helper method to define mock.On call
//   - email usermodel.UserId
func (_e *IdentityRepository_Expecter) FindIdentity(email interface{}) *IdentityRepository_FindIdentity_Call {
	return &IdentityRepository_FindIdentity_Call{Call: _e.mock.On("FindIdentity", email)}
}

func (_c *IdentityRepository_FindIdentity_Call) Run(run func(email usermodel.UserId)) *IdentityRepository_FindIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(usermodel.UserId))
	})
	return _c
}

func (_c *IdentityRepository_FindIdentity_Call) Return(_a0 *aclcore.Identity, _a1 error) *IdentityRepository_FindIdentity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IdentityRepository_FindIdentity_Call) RunAndReturn(run func(usermodel.UserId) (*aclcore.Identity, error)) *IdentityRepository_FindIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// StoreIdentity provides a mock function with given fields: identity
func (_m *IdentityRepository) StoreIdentity(identity aclcore.Identity) error {
	ret := _m.Called(identity)

	if len(ret) == 0 {
		panic("no return value specified for StoreIdentity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(aclcore.Identity) error); ok {
		r0 = rf(identity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IdentityRepository_StoreIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreIdentity'
type IdentityRepository_StoreIdentity_Call struct {
	*mock.Call
}

// StoreIdentity is a helper method to define mock.On call
//   - identity aclcore.Identity
func (_e *IdentityRepository_Expecter) StoreIdentity(identity interface{}) *IdentityRepository_StoreIdentity_Call {
	return &IdentityRepository_StoreIdentity_Call{Call: _e.mock.On("StoreIdentity", identity)}
}

func (_c *IdentityRepository_StoreIdentity_Call) Run(run func(identity aclcore.Identity)) *IdentityRepository_StoreIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(aclcore.Identity))
	})
	return _c
}

func (_c *IdentityRepository_StoreIdentity_Call) Return(_a0 error) *IdentityRepository_StoreIdentity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IdentityRepository_StoreIdentity_Call) RunAndReturn(run func(aclcore.Identity) error) *IdentityRepository_StoreIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// NewIdentityRepository creates a new instance of IdentityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityRepository {
	mock := &IdentityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
