// Code generated by mockery v2.40.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	aclcore "github.com/thomasduchatelle/dphoto/pkg/acl/aclcore"
)

// IdentityQueriesIdentityRepository is an autogenerated mock type for the IdentityQueriesIdentityRepository type
type IdentityQueriesIdentityRepository struct {
	mock.Mock
}

// FindIdentities provides a mock function with given fields: emails
func (_m *IdentityQueriesIdentityRepository) FindIdentities(emails []string) ([]*aclcore.Identity, error) {
	ret := _m.Called(emails)

	if len(ret) == 0 {
		panic("no return value specified for FindIdentities")
	}

	var r0 []*aclcore.Identity
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]*aclcore.Identity, error)); ok {
		return rf(emails)
	}
	if rf, ok := ret.Get(0).(func([]string) []*aclcore.Identity); ok {
		r0 = rf(emails)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aclcore.Identity)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(emails)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIdentityQueriesIdentityRepository creates a new instance of IdentityQueriesIdentityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityQueriesIdentityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityQueriesIdentityRepository {
	mock := &IdentityQueriesIdentityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
