// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	config "github.com/thomasduchatelle/dphoto/cmd/dphoto/config"
)

// Listener is an autogenerated mock type for the Listener type
type Listener struct {
	mock.Mock
}

type Listener_Expecter struct {
	mock *mock.Mock
}

func (_m *Listener) EXPECT() *Listener_Expecter {
	return &Listener_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *Listener) Execute(_a0 config.Config) {
	_m.Called(_a0)
}

// Listener_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type Listener_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 config.Config
func (_e *Listener_Expecter) Execute(_a0 interface{}) *Listener_Execute_Call {
	return &Listener_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *Listener_Execute_Call) Run(run func(_a0 config.Config)) *Listener_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.Config))
	})
	return _c
}

func (_c *Listener_Execute_Call) Return() *Listener_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *Listener_Execute_Call) RunAndReturn(run func(config.Config)) *Listener_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewListener creates a new instance of Listener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *Listener {
	mock := &Listener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
