// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MediaAlbumResolver is an autogenerated mock type for the MediaAlbumResolver type
type MediaAlbumResolver struct {
	mock.Mock
}

type MediaAlbumResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MediaAlbumResolver) EXPECT() *MediaAlbumResolver_Expecter {
	return &MediaAlbumResolver_Expecter{mock: &_m.Mock}
}

// FindAlbumOfMedia provides a mock function with given fields: owner, mediaId
func (_m *MediaAlbumResolver) FindAlbumOfMedia(owner string, mediaId string) (string, error) {
	ret := _m.Called(owner, mediaId)

	if len(ret) == 0 {
		panic("no return value specified for FindAlbumOfMedia")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(owner, mediaId)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(owner, mediaId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(owner, mediaId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MediaAlbumResolver_FindAlbumOfMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAlbumOfMedia'
type MediaAlbumResolver_FindAlbumOfMedia_Call struct {
	*mock.Call
}

// FindAlbumOfMedia is a helper method to define mock.On call
//   - owner string
//   - mediaId string
func (_e *MediaAlbumResolver_Expecter) FindAlbumOfMedia(owner interface{}, mediaId interface{}) *MediaAlbumResolver_FindAlbumOfMedia_Call {
	return &MediaAlbumResolver_FindAlbumOfMedia_Call{Call: _e.mock.On("FindAlbumOfMedia", owner, mediaId)}
}

func (_c *MediaAlbumResolver_FindAlbumOfMedia_Call) Run(run func(owner string, mediaId string)) *MediaAlbumResolver_FindAlbumOfMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MediaAlbumResolver_FindAlbumOfMedia_Call) Return(_a0 string, _a1 error) *MediaAlbumResolver_FindAlbumOfMedia_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MediaAlbumResolver_FindAlbumOfMedia_Call) RunAndReturn(run func(string, string) (string, error)) *MediaAlbumResolver_FindAlbumOfMedia_Call {
	_c.Call.Return(run)
	return _c
}

// NewMediaAlbumResolver creates a new instance of MediaAlbumResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaAlbumResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaAlbumResolver {
	mock := &MediaAlbumResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
