// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/thomasduchatelle/dphoto/pkg/catalog"

	mock "github.com/stretchr/testify/mock"
)

// MoveMediaPortFunc is an autogenerated mock type for the MoveMediaPortFunc type
type MoveMediaPortFunc struct {
	mock.Mock
}

type MoveMediaPortFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MoveMediaPortFunc) EXPECT() *MoveMediaPortFunc_Expecter {
	return &MoveMediaPortFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, albumId, mediaIds
func (_m *MoveMediaPortFunc) Execute(ctx context.Context, albumId catalog.AlbumId, mediaIds []catalog.MediaId) error {
	ret := _m.Called(ctx, albumId, mediaIds)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.AlbumId, []catalog.MediaId) error); ok {
		r0 = rf(ctx, albumId, mediaIds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MoveMediaPortFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MoveMediaPortFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - albumId catalog.AlbumId
//   - mediaIds []catalog.MediaId
func (_e *MoveMediaPortFunc_Expecter) Execute(ctx interface{}, albumId interface{}, mediaIds interface{}) *MoveMediaPortFunc_Execute_Call {
	return &MoveMediaPortFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, albumId, mediaIds)}
}

func (_c *MoveMediaPortFunc_Execute_Call) Run(run func(ctx context.Context, albumId catalog.AlbumId, mediaIds []catalog.MediaId)) *MoveMediaPortFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.AlbumId), args[2].([]catalog.MediaId))
	})
	return _c
}

func (_c *MoveMediaPortFunc_Execute_Call) Return(_a0 error) *MoveMediaPortFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MoveMediaPortFunc_Execute_Call) RunAndReturn(run func(context.Context, catalog.AlbumId, []catalog.MediaId) error) *MoveMediaPortFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMoveMediaPortFunc creates a new instance of MoveMediaPortFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMoveMediaPortFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MoveMediaPortFunc {
	mock := &MoveMediaPortFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
