// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/thomasduchatelle/dphoto/pkg/catalog"

	mock "github.com/stretchr/testify/mock"
)

// RenameAlbumObserver is an autogenerated mock type for the RenameAlbumObserver type
type RenameAlbumObserver struct {
	mock.Mock
}

type RenameAlbumObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *RenameAlbumObserver) EXPECT() *RenameAlbumObserver_Expecter {
	return &RenameAlbumObserver_Expecter{mock: &_m.Mock}
}

// OnRenameAlbum provides a mock function with given fields: ctx, current, creationRequest
func (_m *RenameAlbumObserver) OnRenameAlbum(ctx context.Context, current catalog.AlbumId, creationRequest catalog.CreateAlbumRequest) error {
	ret := _m.Called(ctx, current, creationRequest)

	if len(ret) == 0 {
		panic("no return value specified for OnRenameAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.AlbumId, catalog.CreateAlbumRequest) error); ok {
		r0 = rf(ctx, current, creationRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RenameAlbumObserver_OnRenameAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnRenameAlbum'
type RenameAlbumObserver_OnRenameAlbum_Call struct {
	*mock.Call
}

// OnRenameAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - current catalog.AlbumId
//   - creationRequest catalog.CreateAlbumRequest
func (_e *RenameAlbumObserver_Expecter) OnRenameAlbum(ctx interface{}, current interface{}, creationRequest interface{}) *RenameAlbumObserver_OnRenameAlbum_Call {
	return &RenameAlbumObserver_OnRenameAlbum_Call{Call: _e.mock.On("OnRenameAlbum", ctx, current, creationRequest)}
}

func (_c *RenameAlbumObserver_OnRenameAlbum_Call) Run(run func(ctx context.Context, current catalog.AlbumId, creationRequest catalog.CreateAlbumRequest)) *RenameAlbumObserver_OnRenameAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.AlbumId), args[2].(catalog.CreateAlbumRequest))
	})
	return _c
}

func (_c *RenameAlbumObserver_OnRenameAlbum_Call) Return(_a0 error) *RenameAlbumObserver_OnRenameAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RenameAlbumObserver_OnRenameAlbum_Call) RunAndReturn(run func(context.Context, catalog.AlbumId, catalog.CreateAlbumRequest) error) *RenameAlbumObserver_OnRenameAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewRenameAlbumObserver creates a new instance of RenameAlbumObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRenameAlbumObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *RenameAlbumObserver {
	mock := &RenameAlbumObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
