// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	catalog "github.com/thomasduchatelle/dphoto/pkg/catalog"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryContract is an autogenerated mock type for the RepositoryContract type
type RepositoryContract struct {
	mock.Mock
}

type RepositoryContract_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryContract) EXPECT() *RepositoryContract_Expecter {
	return &RepositoryContract_Expecter{mock: &_m.Mock}
}

// DeleteEmptyAlbum provides a mock function with given fields: ctx, id
func (_m *RepositoryContract) DeleteEmptyAlbum(ctx context.Context, id catalog.AlbumId) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEmptyAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.AlbumId) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryContract_DeleteEmptyAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEmptyAlbum'
type RepositoryContract_DeleteEmptyAlbum_Call struct {
	*mock.Call
}

// DeleteEmptyAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - id catalog.AlbumId
func (_e *RepositoryContract_Expecter) DeleteEmptyAlbum(ctx interface{}, id interface{}) *RepositoryContract_DeleteEmptyAlbum_Call {
	return &RepositoryContract_DeleteEmptyAlbum_Call{Call: _e.mock.On("DeleteEmptyAlbum", ctx, id)}
}

func (_c *RepositoryContract_DeleteEmptyAlbum_Call) Run(run func(ctx context.Context, id catalog.AlbumId)) *RepositoryContract_DeleteEmptyAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.AlbumId))
	})
	return _c
}

func (_c *RepositoryContract_DeleteEmptyAlbum_Call) Return(_a0 error) *RepositoryContract_DeleteEmptyAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryContract_DeleteEmptyAlbum_Call) RunAndReturn(run func(context.Context, catalog.AlbumId) error) *RepositoryContract_DeleteEmptyAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// FindAlbums provides a mock function with given fields: ctx, ids
func (_m *RepositoryContract) FindAlbums(ctx context.Context, ids ...catalog.AlbumId) ([]*catalog.Album, error) {
	_va := make([]interface{}, len(ids))
	for _i := range ids {
		_va[_i] = ids[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindAlbums")
	}

	var r0 []*catalog.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...catalog.AlbumId) ([]*catalog.Album, error)); ok {
		return rf(ctx, ids...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...catalog.AlbumId) []*catalog.Album); ok {
		r0 = rf(ctx, ids...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*catalog.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...catalog.AlbumId) error); ok {
		r1 = rf(ctx, ids...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryContract_FindAlbums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAlbums'
type RepositoryContract_FindAlbums_Call struct {
	*mock.Call
}

// FindAlbums is a helper method to define mock.On call
//   - ctx context.Context
//   - ids ...catalog.AlbumId
func (_e *RepositoryContract_Expecter) FindAlbums(ctx interface{}, ids ...interface{}) *RepositoryContract_FindAlbums_Call {
	return &RepositoryContract_FindAlbums_Call{Call: _e.mock.On("FindAlbums",
		append([]interface{}{ctx}, ids...)...)}
}

func (_c *RepositoryContract_FindAlbums_Call) Run(run func(ctx context.Context, ids ...catalog.AlbumId)) *RepositoryContract_FindAlbums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]catalog.AlbumId, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(catalog.AlbumId)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *RepositoryContract_FindAlbums_Call) Return(_a0 []*catalog.Album, _a1 error) *RepositoryContract_FindAlbums_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryContract_FindAlbums_Call) RunAndReturn(run func(context.Context, ...catalog.AlbumId) ([]*catalog.Album, error)) *RepositoryContract_FindAlbums_Call {
	_c.Call.Return(run)
	return _c
}

// FindAlbumsByOwner provides a mock function with given fields: ctx, owner
func (_m *RepositoryContract) FindAlbumsByOwner(ctx context.Context, owner catalog.Owner) ([]*catalog.Album, error) {
	ret := _m.Called(ctx, owner)

	if len(ret) == 0 {
		panic("no return value specified for FindAlbumsByOwner")
	}

	var r0 []*catalog.Album
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Owner) ([]*catalog.Album, error)); ok {
		return rf(ctx, owner)
	}
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Owner) []*catalog.Album); ok {
		r0 = rf(ctx, owner)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*catalog.Album)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, catalog.Owner) error); ok {
		r1 = rf(ctx, owner)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryContract_FindAlbumsByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAlbumsByOwner'
type RepositoryContract_FindAlbumsByOwner_Call struct {
	*mock.Call
}

// FindAlbumsByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - owner catalog.Owner
func (_e *RepositoryContract_Expecter) FindAlbumsByOwner(ctx interface{}, owner interface{}) *RepositoryContract_FindAlbumsByOwner_Call {
	return &RepositoryContract_FindAlbumsByOwner_Call{Call: _e.mock.On("FindAlbumsByOwner", ctx, owner)}
}

func (_c *RepositoryContract_FindAlbumsByOwner_Call) Run(run func(ctx context.Context, owner catalog.Owner)) *RepositoryContract_FindAlbumsByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.Owner))
	})
	return _c
}

func (_c *RepositoryContract_FindAlbumsByOwner_Call) Return(_a0 []*catalog.Album, _a1 error) *RepositoryContract_FindAlbumsByOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryContract_FindAlbumsByOwner_Call) RunAndReturn(run func(context.Context, catalog.Owner) ([]*catalog.Album, error)) *RepositoryContract_FindAlbumsByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// FindExistingSignatures provides a mock function with given fields: ctx, owner, signatures
func (_m *RepositoryContract) FindExistingSignatures(ctx context.Context, owner catalog.Owner, signatures []*catalog.MediaSignature) ([]*catalog.MediaSignature, error) {
	ret := _m.Called(ctx, owner, signatures)

	if len(ret) == 0 {
		panic("no return value specified for FindExistingSignatures")
	}

	var r0 []*catalog.MediaSignature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Owner, []*catalog.MediaSignature) ([]*catalog.MediaSignature, error)); ok {
		return rf(ctx, owner, signatures)
	}
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Owner, []*catalog.MediaSignature) []*catalog.MediaSignature); ok {
		r0 = rf(ctx, owner, signatures)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*catalog.MediaSignature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, catalog.Owner, []*catalog.MediaSignature) error); ok {
		r1 = rf(ctx, owner, signatures)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryContract_FindExistingSignatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExistingSignatures'
type RepositoryContract_FindExistingSignatures_Call struct {
	*mock.Call
}

// FindExistingSignatures is a helper method to define mock.On call
//   - ctx context.Context
//   - owner catalog.Owner
//   - signatures []*catalog.MediaSignature
func (_e *RepositoryContract_Expecter) FindExistingSignatures(ctx interface{}, owner interface{}, signatures interface{}) *RepositoryContract_FindExistingSignatures_Call {
	return &RepositoryContract_FindExistingSignatures_Call{Call: _e.mock.On("FindExistingSignatures", ctx, owner, signatures)}
}

func (_c *RepositoryContract_FindExistingSignatures_Call) Run(run func(ctx context.Context, owner catalog.Owner, signatures []*catalog.MediaSignature)) *RepositoryContract_FindExistingSignatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.Owner), args[2].([]*catalog.MediaSignature))
	})
	return _c
}

func (_c *RepositoryContract_FindExistingSignatures_Call) Return(_a0 []*catalog.MediaSignature, _a1 error) *RepositoryContract_FindExistingSignatures_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryContract_FindExistingSignatures_Call) RunAndReturn(run func(context.Context, catalog.Owner, []*catalog.MediaSignature) ([]*catalog.MediaSignature, error)) *RepositoryContract_FindExistingSignatures_Call {
	_c.Call.Return(run)
	return _c
}

// FindMediaCurrentAlbum provides a mock function with given fields: ctx, owner, mediaId
func (_m *RepositoryContract) FindMediaCurrentAlbum(ctx context.Context, owner catalog.Owner, mediaId catalog.MediaId) (*catalog.AlbumId, error) {
	ret := _m.Called(ctx, owner, mediaId)

	if len(ret) == 0 {
		panic("no return value specified for FindMediaCurrentAlbum")
	}

	var r0 *catalog.AlbumId
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Owner, catalog.MediaId) (*catalog.AlbumId, error)); ok {
		return rf(ctx, owner, mediaId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Owner, catalog.MediaId) *catalog.AlbumId); ok {
		r0 = rf(ctx, owner, mediaId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.AlbumId)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, catalog.Owner, catalog.MediaId) error); ok {
		r1 = rf(ctx, owner, mediaId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryContract_FindMediaCurrentAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMediaCurrentAlbum'
type RepositoryContract_FindMediaCurrentAlbum_Call struct {
	*mock.Call
}

// FindMediaCurrentAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - owner catalog.Owner
//   - mediaId catalog.MediaId
func (_e *RepositoryContract_Expecter) FindMediaCurrentAlbum(ctx interface{}, owner interface{}, mediaId interface{}) *RepositoryContract_FindMediaCurrentAlbum_Call {
	return &RepositoryContract_FindMediaCurrentAlbum_Call{Call: _e.mock.On("FindMediaCurrentAlbum", ctx, owner, mediaId)}
}

func (_c *RepositoryContract_FindMediaCurrentAlbum_Call) Run(run func(ctx context.Context, owner catalog.Owner, mediaId catalog.MediaId)) *RepositoryContract_FindMediaCurrentAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.Owner), args[2].(catalog.MediaId))
	})
	return _c
}

func (_c *RepositoryContract_FindMediaCurrentAlbum_Call) Return(id *catalog.AlbumId, err error) *RepositoryContract_FindMediaCurrentAlbum_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *RepositoryContract_FindMediaCurrentAlbum_Call) RunAndReturn(run func(context.Context, catalog.Owner, catalog.MediaId) (*catalog.AlbumId, error)) *RepositoryContract_FindMediaCurrentAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// FindMediaIds provides a mock function with given fields: ctx, request
func (_m *RepositoryContract) FindMediaIds(ctx context.Context, request *catalog.FindMediaRequest) ([]catalog.MediaId, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for FindMediaIds")
	}

	var r0 []catalog.MediaId
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.FindMediaRequest) ([]catalog.MediaId, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.FindMediaRequest) []catalog.MediaId); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.MediaId)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *catalog.FindMediaRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryContract_FindMediaIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMediaIds'
type RepositoryContract_FindMediaIds_Call struct {
	*mock.Call
}

// FindMediaIds is a helper method to define mock.On call
//   - ctx context.Context
//   - request *catalog.FindMediaRequest
func (_e *RepositoryContract_Expecter) FindMediaIds(ctx interface{}, request interface{}) *RepositoryContract_FindMediaIds_Call {
	return &RepositoryContract_FindMediaIds_Call{Call: _e.mock.On("FindMediaIds", ctx, request)}
}

func (_c *RepositoryContract_FindMediaIds_Call) Run(run func(ctx context.Context, request *catalog.FindMediaRequest)) *RepositoryContract_FindMediaIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*catalog.FindMediaRequest))
	})
	return _c
}

func (_c *RepositoryContract_FindMediaIds_Call) Return(ids []catalog.MediaId, err error) *RepositoryContract_FindMediaIds_Call {
	_c.Call.Return(ids, err)
	return _c
}

func (_c *RepositoryContract_FindMediaIds_Call) RunAndReturn(run func(context.Context, *catalog.FindMediaRequest) ([]catalog.MediaId, error)) *RepositoryContract_FindMediaIds_Call {
	_c.Call.Return(run)
	return _c
}

// FindMedias provides a mock function with given fields: ctx, request
func (_m *RepositoryContract) FindMedias(ctx context.Context, request *catalog.FindMediaRequest) ([]*catalog.MediaMeta, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for FindMedias")
	}

	var r0 []*catalog.MediaMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.FindMediaRequest) ([]*catalog.MediaMeta, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.FindMediaRequest) []*catalog.MediaMeta); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*catalog.MediaMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *catalog.FindMediaRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryContract_FindMedias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMedias'
type RepositoryContract_FindMedias_Call struct {
	*mock.Call
}

// FindMedias is a helper method to define mock.On call
//   - ctx context.Context
//   - request *catalog.FindMediaRequest
func (_e *RepositoryContract_Expecter) FindMedias(ctx interface{}, request interface{}) *RepositoryContract_FindMedias_Call {
	return &RepositoryContract_FindMedias_Call{Call: _e.mock.On("FindMedias", ctx, request)}
}

func (_c *RepositoryContract_FindMedias_Call) Run(run func(ctx context.Context, request *catalog.FindMediaRequest)) *RepositoryContract_FindMedias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*catalog.FindMediaRequest))
	})
	return _c
}

func (_c *RepositoryContract_FindMedias_Call) Return(medias []*catalog.MediaMeta, err error) *RepositoryContract_FindMedias_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *RepositoryContract_FindMedias_Call) RunAndReturn(run func(context.Context, *catalog.FindMediaRequest) ([]*catalog.MediaMeta, error)) *RepositoryContract_FindMedias_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAlbum provides a mock function with given fields: ctx, album
func (_m *RepositoryContract) InsertAlbum(ctx context.Context, album catalog.Album) error {
	ret := _m.Called(ctx, album)

	if len(ret) == 0 {
		panic("no return value specified for InsertAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Album) error); ok {
		r0 = rf(ctx, album)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryContract_InsertAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAlbum'
type RepositoryContract_InsertAlbum_Call struct {
	*mock.Call
}

// InsertAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - album catalog.Album
func (_e *RepositoryContract_Expecter) InsertAlbum(ctx interface{}, album interface{}) *RepositoryContract_InsertAlbum_Call {
	return &RepositoryContract_InsertAlbum_Call{Call: _e.mock.On("InsertAlbum", ctx, album)}
}

func (_c *RepositoryContract_InsertAlbum_Call) Run(run func(ctx context.Context, album catalog.Album)) *RepositoryContract_InsertAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.Album))
	})
	return _c
}

func (_c *RepositoryContract_InsertAlbum_Call) Return(_a0 error) *RepositoryContract_InsertAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryContract_InsertAlbum_Call) RunAndReturn(run func(context.Context, catalog.Album) error) *RepositoryContract_InsertAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMedias provides a mock function with given fields: ctx, owner, media
func (_m *RepositoryContract) InsertMedias(ctx context.Context, owner catalog.Owner, media []catalog.CreateMediaRequest) error {
	ret := _m.Called(ctx, owner, media)

	if len(ret) == 0 {
		panic("no return value specified for InsertMedias")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Owner, []catalog.CreateMediaRequest) error); ok {
		r0 = rf(ctx, owner, media)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryContract_InsertMedias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMedias'
type RepositoryContract_InsertMedias_Call struct {
	*mock.Call
}

// InsertMedias is a helper method to define mock.On call
//   - ctx context.Context
//   - owner catalog.Owner
//   - media []catalog.CreateMediaRequest
func (_e *RepositoryContract_Expecter) InsertMedias(ctx interface{}, owner interface{}, media interface{}) *RepositoryContract_InsertMedias_Call {
	return &RepositoryContract_InsertMedias_Call{Call: _e.mock.On("InsertMedias", ctx, owner, media)}
}

func (_c *RepositoryContract_InsertMedias_Call) Run(run func(ctx context.Context, owner catalog.Owner, media []catalog.CreateMediaRequest)) *RepositoryContract_InsertMedias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.Owner), args[2].([]catalog.CreateMediaRequest))
	})
	return _c
}

func (_c *RepositoryContract_InsertMedias_Call) Return(_a0 error) *RepositoryContract_InsertMedias_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryContract_InsertMedias_Call) RunAndReturn(run func(context.Context, catalog.Owner, []catalog.CreateMediaRequest) error) *RepositoryContract_InsertMedias_Call {
	_c.Call.Return(run)
	return _c
}

// TransferMedias provides a mock function with given fields: ctx, owner, mediaIds, newFolderName
func (_m *RepositoryContract) TransferMedias(ctx context.Context, owner catalog.Owner, mediaIds []catalog.MediaId, newFolderName catalog.FolderName) error {
	ret := _m.Called(ctx, owner, mediaIds, newFolderName)

	if len(ret) == 0 {
		panic("no return value specified for TransferMedias")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Owner, []catalog.MediaId, catalog.FolderName) error); ok {
		r0 = rf(ctx, owner, mediaIds, newFolderName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryContract_TransferMedias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferMedias'
type RepositoryContract_TransferMedias_Call struct {
	*mock.Call
}

// TransferMedias is a helper method to define mock.On call
//   - ctx context.Context
//   - owner catalog.Owner
//   - mediaIds []catalog.MediaId
//   - newFolderName catalog.FolderName
func (_e *RepositoryContract_Expecter) TransferMedias(ctx interface{}, owner interface{}, mediaIds interface{}, newFolderName interface{}) *RepositoryContract_TransferMedias_Call {
	return &RepositoryContract_TransferMedias_Call{Call: _e.mock.On("TransferMedias", ctx, owner, mediaIds, newFolderName)}
}

func (_c *RepositoryContract_TransferMedias_Call) Run(run func(ctx context.Context, owner catalog.Owner, mediaIds []catalog.MediaId, newFolderName catalog.FolderName)) *RepositoryContract_TransferMedias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.Owner), args[2].([]catalog.MediaId), args[3].(catalog.FolderName))
	})
	return _c
}

func (_c *RepositoryContract_TransferMedias_Call) Return(_a0 error) *RepositoryContract_TransferMedias_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryContract_TransferMedias_Call) RunAndReturn(run func(context.Context, catalog.Owner, []catalog.MediaId, catalog.FolderName) error) *RepositoryContract_TransferMedias_Call {
	_c.Call.Return(run)
	return _c
}

// TransferMediasFromRecords provides a mock function with given fields: ctx, records
func (_m *RepositoryContract) TransferMediasFromRecords(ctx context.Context, records catalog.MediaTransferRecords) (catalog.TransferredMedias, error) {
	ret := _m.Called(ctx, records)

	if len(ret) == 0 {
		panic("no return value specified for TransferMediasFromRecords")
	}

	var r0 catalog.TransferredMedias
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.MediaTransferRecords) (catalog.TransferredMedias, error)); ok {
		return rf(ctx, records)
	}
	if rf, ok := ret.Get(0).(func(context.Context, catalog.MediaTransferRecords) catalog.TransferredMedias); ok {
		r0 = rf(ctx, records)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(catalog.TransferredMedias)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, catalog.MediaTransferRecords) error); ok {
		r1 = rf(ctx, records)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryContract_TransferMediasFromRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferMediasFromRecords'
type RepositoryContract_TransferMediasFromRecords_Call struct {
	*mock.Call
}

// TransferMediasFromRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - records catalog.MediaTransferRecords
func (_e *RepositoryContract_Expecter) TransferMediasFromRecords(ctx interface{}, records interface{}) *RepositoryContract_TransferMediasFromRecords_Call {
	return &RepositoryContract_TransferMediasFromRecords_Call{Call: _e.mock.On("TransferMediasFromRecords", ctx, records)}
}

func (_c *RepositoryContract_TransferMediasFromRecords_Call) Run(run func(ctx context.Context, records catalog.MediaTransferRecords)) *RepositoryContract_TransferMediasFromRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.MediaTransferRecords))
	})
	return _c
}

func (_c *RepositoryContract_TransferMediasFromRecords_Call) Return(_a0 catalog.TransferredMedias, _a1 error) *RepositoryContract_TransferMediasFromRecords_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryContract_TransferMediasFromRecords_Call) RunAndReturn(run func(context.Context, catalog.MediaTransferRecords) (catalog.TransferredMedias, error)) *RepositoryContract_TransferMediasFromRecords_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAlbum provides a mock function with given fields: ctx, album
func (_m *RepositoryContract) UpdateAlbum(ctx context.Context, album catalog.Album) error {
	ret := _m.Called(ctx, album)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAlbum")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, catalog.Album) error); ok {
		r0 = rf(ctx, album)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryContract_UpdateAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAlbum'
type RepositoryContract_UpdateAlbum_Call struct {
	*mock.Call
}

// UpdateAlbum is a helper method to define mock.On call
//   - ctx context.Context
//   - album catalog.Album
func (_e *RepositoryContract_Expecter) UpdateAlbum(ctx interface{}, album interface{}) *RepositoryContract_UpdateAlbum_Call {
	return &RepositoryContract_UpdateAlbum_Call{Call: _e.mock.On("UpdateAlbum", ctx, album)}
}

func (_c *RepositoryContract_UpdateAlbum_Call) Run(run func(ctx context.Context, album catalog.Album)) *RepositoryContract_UpdateAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(catalog.Album))
	})
	return _c
}

func (_c *RepositoryContract_UpdateAlbum_Call) Return(_a0 error) *RepositoryContract_UpdateAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryContract_UpdateAlbum_Call) RunAndReturn(run func(context.Context, catalog.Album) error) *RepositoryContract_UpdateAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryContract creates a new instance of RepositoryContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryContract(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryContract {
	mock := &RepositoryContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
