// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RevokeAccessTokenAdapter is an autogenerated mock type for the RevokeAccessTokenAdapter type
type RevokeAccessTokenAdapter struct {
	mock.Mock
}

// DeleteRefreshToken provides a mock function with given fields: token
func (_m *RevokeAccessTokenAdapter) DeleteRefreshToken(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRevokeAccessTokenAdapter creates a new instance of RevokeAccessTokenAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRevokeAccessTokenAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RevokeAccessTokenAdapter {
	mock := &RevokeAccessTokenAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
