// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	backup "github.com/thomasduchatelle/dphoto/pkg/backup"
)

// RunnerAnalyserFunc is an autogenerated mock type for the RunnerAnalyserFunc type
type RunnerAnalyserFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: found, progressChannel
func (_m *RunnerAnalyserFunc) Execute(found backup.FoundMedia, progressChannel chan *backup.ProgressEvent) (*backup.AnalysedMedia, error) {
	ret := _m.Called(found, progressChannel)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *backup.AnalysedMedia
	var r1 error
	if rf, ok := ret.Get(0).(func(backup.FoundMedia, chan *backup.ProgressEvent) (*backup.AnalysedMedia, error)); ok {
		return rf(found, progressChannel)
	}
	if rf, ok := ret.Get(0).(func(backup.FoundMedia, chan *backup.ProgressEvent) *backup.AnalysedMedia); ok {
		r0 = rf(found, progressChannel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backup.AnalysedMedia)
		}
	}

	if rf, ok := ret.Get(1).(func(backup.FoundMedia, chan *backup.ProgressEvent) error); ok {
		r1 = rf(found, progressChannel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRunnerAnalyserFunc creates a new instance of RunnerAnalyserFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunnerAnalyserFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *RunnerAnalyserFunc {
	mock := &RunnerAnalyserFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
