// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	backup "github.com/thomasduchatelle/dphoto/pkg/backup"
)

// runnerCataloger is an autogenerated mock type for the runnerCataloger type
type runnerCataloger struct {
	mock.Mock
}

type runnerCataloger_Expecter struct {
	mock *mock.Mock
}

func (_m *runnerCataloger) EXPECT() *runnerCataloger_Expecter {
	return &runnerCataloger_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: medias, progressChannel
func (_m *runnerCataloger) Execute(medias []*backup.AnalysedMedia, progressChannel chan *backup.ProgressEvent) ([]*backup.BackingUpMediaRequest, error) {
	ret := _m.Called(medias, progressChannel)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*backup.BackingUpMediaRequest
	var r1 error
	if rf, ok := ret.Get(0).(func([]*backup.AnalysedMedia, chan *backup.ProgressEvent) ([]*backup.BackingUpMediaRequest, error)); ok {
		return rf(medias, progressChannel)
	}
	if rf, ok := ret.Get(0).(func([]*backup.AnalysedMedia, chan *backup.ProgressEvent) []*backup.BackingUpMediaRequest); ok {
		r0 = rf(medias, progressChannel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*backup.BackingUpMediaRequest)
		}
	}

	if rf, ok := ret.Get(1).(func([]*backup.AnalysedMedia, chan *backup.ProgressEvent) error); ok {
		r1 = rf(medias, progressChannel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// runnerCataloger_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type runnerCataloger_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - medias []*backup.AnalysedMedia
//   - progressChannel chan *backup.ProgressEvent
func (_e *runnerCataloger_Expecter) Execute(medias interface{}, progressChannel interface{}) *runnerCataloger_Execute_Call {
	return &runnerCataloger_Execute_Call{Call: _e.mock.On("Execute", medias, progressChannel)}
}

func (_c *runnerCataloger_Execute_Call) Run(run func(medias []*backup.AnalysedMedia, progressChannel chan *backup.ProgressEvent)) *runnerCataloger_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*backup.AnalysedMedia), args[1].(chan *backup.ProgressEvent))
	})
	return _c
}

func (_c *runnerCataloger_Execute_Call) Return(_a0 []*backup.BackingUpMediaRequest, _a1 error) *runnerCataloger_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *runnerCataloger_Execute_Call) RunAndReturn(run func([]*backup.AnalysedMedia, chan *backup.ProgressEvent) ([]*backup.BackingUpMediaRequest, error)) *runnerCataloger_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newRunnerCataloger creates a new instance of runnerCataloger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newRunnerCataloger(t interface {
	mock.TestingT
	Cleanup(func())
}) *runnerCataloger {
	mock := &runnerCataloger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
