// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	aclcore "github.com/thomasduchatelle/dphoto/pkg/acl/aclcore"

	mock "github.com/stretchr/testify/mock"

	ownermodel "github.com/thomasduchatelle/dphoto/pkg/ownermodel"

	usermodel "github.com/thomasduchatelle/dphoto/pkg/usermodel"
)

// ScopeRepository is an autogenerated mock type for the ScopeRepository type
type ScopeRepository struct {
	mock.Mock
}

type ScopeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ScopeRepository) EXPECT() *ScopeRepository_Expecter {
	return &ScopeRepository_Expecter{mock: &_m.Mock}
}

// FindScopesById provides a mock function with given fields: ids
func (_m *ScopeRepository) FindScopesById(ids ...aclcore.ScopeId) ([]*aclcore.Scope, error) {
	_va := make([]interface{}, len(ids))
	for _i := range ids {
		_va[_i] = ids[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FindScopesById")
	}

	var r0 []*aclcore.Scope
	var r1 error
	if rf, ok := ret.Get(0).(func(...aclcore.ScopeId) ([]*aclcore.Scope, error)); ok {
		return rf(ids...)
	}
	if rf, ok := ret.Get(0).(func(...aclcore.ScopeId) []*aclcore.Scope); ok {
		r0 = rf(ids...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aclcore.Scope)
		}
	}

	if rf, ok := ret.Get(1).(func(...aclcore.ScopeId) error); ok {
		r1 = rf(ids...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScopeRepository_FindScopesById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindScopesById'
type ScopeRepository_FindScopesById_Call struct {
	*mock.Call
}

// FindScopesById is a helper method to define mock.On call
//   - ids ...aclcore.ScopeId
func (_e *ScopeRepository_Expecter) FindScopesById(ids ...interface{}) *ScopeRepository_FindScopesById_Call {
	return &ScopeRepository_FindScopesById_Call{Call: _e.mock.On("FindScopesById",
		append([]interface{}{}, ids...)...)}
}

func (_c *ScopeRepository_FindScopesById_Call) Run(run func(ids ...aclcore.ScopeId)) *ScopeRepository_FindScopesById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]aclcore.ScopeId, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(aclcore.ScopeId)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *ScopeRepository_FindScopesById_Call) Return(_a0 []*aclcore.Scope, _a1 error) *ScopeRepository_FindScopesById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScopeRepository_FindScopesById_Call) RunAndReturn(run func(...aclcore.ScopeId) ([]*aclcore.Scope, error)) *ScopeRepository_FindScopesById_Call {
	_c.Call.Return(run)
	return _c
}

// ListOwnerScopes provides a mock function with given fields: owner, types
func (_m *ScopeRepository) ListOwnerScopes(owner ownermodel.Owner, types ...aclcore.ScopeType) ([]*aclcore.Scope, error) {
	_va := make([]interface{}, len(types))
	for _i := range types {
		_va[_i] = types[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, owner)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListOwnerScopes")
	}

	var r0 []*aclcore.Scope
	var r1 error
	if rf, ok := ret.Get(0).(func(ownermodel.Owner, ...aclcore.ScopeType) ([]*aclcore.Scope, error)); ok {
		return rf(owner, types...)
	}
	if rf, ok := ret.Get(0).(func(ownermodel.Owner, ...aclcore.ScopeType) []*aclcore.Scope); ok {
		r0 = rf(owner, types...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aclcore.Scope)
		}
	}

	if rf, ok := ret.Get(1).(func(ownermodel.Owner, ...aclcore.ScopeType) error); ok {
		r1 = rf(owner, types...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScopeRepository_ListOwnerScopes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOwnerScopes'
type ScopeRepository_ListOwnerScopes_Call struct {
	*mock.Call
}

// ListOwnerScopes is a helper method to define mock.On call
//   - owner ownermodel.Owner
//   - types ...aclcore.ScopeType
func (_e *ScopeRepository_Expecter) ListOwnerScopes(owner interface{}, types ...interface{}) *ScopeRepository_ListOwnerScopes_Call {
	return &ScopeRepository_ListOwnerScopes_Call{Call: _e.mock.On("ListOwnerScopes",
		append([]interface{}{owner}, types...)...)}
}

func (_c *ScopeRepository_ListOwnerScopes_Call) Run(run func(owner ownermodel.Owner, types ...aclcore.ScopeType)) *ScopeRepository_ListOwnerScopes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]aclcore.ScopeType, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(aclcore.ScopeType)
			}
		}
		run(args[0].(ownermodel.Owner), variadicArgs...)
	})
	return _c
}

func (_c *ScopeRepository_ListOwnerScopes_Call) Return(_a0 []*aclcore.Scope, _a1 error) *ScopeRepository_ListOwnerScopes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScopeRepository_ListOwnerScopes_Call) RunAndReturn(run func(ownermodel.Owner, ...aclcore.ScopeType) ([]*aclcore.Scope, error)) *ScopeRepository_ListOwnerScopes_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserScopes provides a mock function with given fields: email, types
func (_m *ScopeRepository) ListUserScopes(email usermodel.UserId, types ...aclcore.ScopeType) ([]*aclcore.Scope, error) {
	_va := make([]interface{}, len(types))
	for _i := range types {
		_va[_i] = types[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, email)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListUserScopes")
	}

	var r0 []*aclcore.Scope
	var r1 error
	if rf, ok := ret.Get(0).(func(usermodel.UserId, ...aclcore.ScopeType) ([]*aclcore.Scope, error)); ok {
		return rf(email, types...)
	}
	if rf, ok := ret.Get(0).(func(usermodel.UserId, ...aclcore.ScopeType) []*aclcore.Scope); ok {
		r0 = rf(email, types...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*aclcore.Scope)
		}
	}

	if rf, ok := ret.Get(1).(func(usermodel.UserId, ...aclcore.ScopeType) error); ok {
		r1 = rf(email, types...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScopeRepository_ListUserScopes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserScopes'
type ScopeRepository_ListUserScopes_Call struct {
	*mock.Call
}

// ListUserScopes is a helper method to define mock.On call
//   - email usermodel.UserId
//   - types ...aclcore.ScopeType
func (_e *ScopeRepository_Expecter) ListUserScopes(email interface{}, types ...interface{}) *ScopeRepository_ListUserScopes_Call {
	return &ScopeRepository_ListUserScopes_Call{Call: _e.mock.On("ListUserScopes",
		append([]interface{}{email}, types...)...)}
}

func (_c *ScopeRepository_ListUserScopes_Call) Run(run func(email usermodel.UserId, types ...aclcore.ScopeType)) *ScopeRepository_ListUserScopes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]aclcore.ScopeType, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(aclcore.ScopeType)
			}
		}
		run(args[0].(usermodel.UserId), variadicArgs...)
	})
	return _c
}

func (_c *ScopeRepository_ListUserScopes_Call) Return(_a0 []*aclcore.Scope, _a1 error) *ScopeRepository_ListUserScopes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScopeRepository_ListUserScopes_Call) RunAndReturn(run func(usermodel.UserId, ...aclcore.ScopeType) ([]*aclcore.Scope, error)) *ScopeRepository_ListUserScopes_Call {
	_c.Call.Return(run)
	return _c
}

// NewScopeRepository creates a new instance of ScopeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScopeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScopeRepository {
	mock := &ScopeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
