// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SecretAccessKeyDecoder is an autogenerated mock type for the SecretAccessKeyDecoder type
type SecretAccessKeyDecoder struct {
	mock.Mock
}

type SecretAccessKeyDecoder_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretAccessKeyDecoder) EXPECT() *SecretAccessKeyDecoder_Expecter {
	return &SecretAccessKeyDecoder_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: encodedValue
func (_m *SecretAccessKeyDecoder) Execute(encodedValue string) (string, error) {
	ret := _m.Called(encodedValue)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(encodedValue)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(encodedValue)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(encodedValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SecretAccessKeyDecoder_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type SecretAccessKeyDecoder_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - encodedValue string
func (_e *SecretAccessKeyDecoder_Expecter) Execute(encodedValue interface{}) *SecretAccessKeyDecoder_Execute_Call {
	return &SecretAccessKeyDecoder_Execute_Call{Call: _e.mock.On("Execute", encodedValue)}
}

func (_c *SecretAccessKeyDecoder_Execute_Call) Run(run func(encodedValue string)) *SecretAccessKeyDecoder_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *SecretAccessKeyDecoder_Execute_Call) Return(_a0 string, _a1 error) *SecretAccessKeyDecoder_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SecretAccessKeyDecoder_Execute_Call) RunAndReturn(run func(string) (string, error)) *SecretAccessKeyDecoder_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewSecretAccessKeyDecoder creates a new instance of SecretAccessKeyDecoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretAccessKeyDecoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretAccessKeyDecoder {
	mock := &SecretAccessKeyDecoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
