// Code generated by mockery v2.3.0. DO NOT EDIT.

package runner

import (
	model "duchatelle.io/dphoto/dphoto/backup/model"
	mock "github.com/stretchr/testify/mock"
)

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

// Execute provides a mock function with given fields: medias
func (_m *MockSource) Execute(medias chan model.FoundMedia) error {
	ret := _m.Called(medias)

	var r0 error
	if rf, ok := ret.Get(0).(func(chan model.FoundMedia) error); ok {
		r0 = rf(medias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
