// Code generated by mockery v2.3.0. DO NOT EDIT.

package scanner

import mock "github.com/stretchr/testify/mock"

// MockFilter is an autogenerated mock type for the Filter type
type MockFilter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: found
func (_m *MockFilter) Execute(found FoundMedia) bool {
	ret := _m.Called(found)

	var r0 bool
	if rf, ok := ret.Get(0).(func(FoundMedia) bool); ok {
		r0 = rf(found)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
