// Code generated by mockery v2.3.0. DO NOT EDIT.

package scanner

import mock "github.com/stretchr/testify/mock"

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

// Execute provides a mock function with given fields: medias
func (_m *MockSource) Execute(medias chan FoundMedia) (uint, uint, error) {
	ret := _m.Called(medias)

	var r0 uint
	if rf, ok := ret.Get(0).(func(chan FoundMedia) uint); ok {
		r0 = rf(medias)
	} else {
		r0 = ret.Get(0).(uint)
	}

	var r1 uint
	if rf, ok := ret.Get(1).(func(chan FoundMedia) uint); ok {
		r1 = rf(medias)
	} else {
		r1 = ret.Get(1).(uint)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(chan FoundMedia) error); ok {
		r2 = rf(medias)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
