// Code generated by mockery v2.3.0. DO NOT EDIT.

package scanner

import mock "github.com/stretchr/testify/mock"

// MockUploader is an autogenerated mock type for the Uploader type
type MockUploader struct {
	mock.Mock
}

// Execute provides a mock function with given fields: buffer, progressChannel
func (_m *MockUploader) Execute(buffer []*AnalysedMedia, progressChannel chan *ProgressEvent) error {
	ret := _m.Called(buffer, progressChannel)

	var r0 error
	if rf, ok := ret.Get(0).(func([]*AnalysedMedia, chan *ProgressEvent) error); ok {
		r0 = rf(buffer, progressChannel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
