// Code generated by mockery v2.3.0. DO NOT EDIT.

package scanner

import (
	io "io"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockImageDetailsReaderAdapter is an autogenerated mock type for the ImageDetailsReaderAdapter type
type MockImageDetailsReaderAdapter struct {
	mock.Mock
}

// ReadImageDetails provides a mock function with given fields: reader, lastModifiedDate
func (_m *MockImageDetailsReaderAdapter) ReadImageDetails(reader io.Reader, lastModifiedDate time.Time) (*MediaDetails, error) {
	ret := _m.Called(reader, lastModifiedDate)

	var r0 *MediaDetails
	if rf, ok := ret.Get(0).(func(io.Reader, time.Time) *MediaDetails); ok {
		r0 = rf(reader, lastModifiedDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MediaDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Reader, time.Time) error); ok {
		r1 = rf(reader, lastModifiedDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
