# Reference: https://aider.chat/docs/config/aider_conf.html

model: bb8

#R2D2 ?? C3PO ??
alias:
  - "chewy:openrouter/meta-llama/llama-4-maverick"            # Chewbacca - always present, strong, but not always reliable.
  - "gaal:openrouter/x-ai/grok-3-beta"                        # Gaal Dornick (Foundation) - follow the trace of Seldon, but needs to prove her worth.
  - "six:openrouter/anthropic/claude-sonnet-4"                # Caprica-Six (Battlestar Galactica) - a strong and reliable model, but not always available.
  - "flash-preview:openrouter/google/gemini-2.5-flash-preview-05-20"    # BB-8 (Star Wars) - a small, but very reliable model, always ready to help.
  - "bb8:openrouter/google/gemini-2.5-flash"
  - "4om:openrouter/openai/gpt-4o-mini"
  - "dc3:openrouter/deepseek/deepseek-chat-v3-0324"
  - "dc3-latest:openrouter/deepseek/deepseek-chat-v3"
  #  - "seldon:"             # Hari Seldon (Foundation) - the smartest of all, but with a cost.

  # CANDIDATES for bb8:
  # openrouter/anthropic/claude-sonnet-4               3.00/15.0
  # openrouter/google/gemini-2.5-flash-preview-05-20   0.15/0.60
  # openrouter/deepseek/deepseek-chat-v3-0324          0.28/0.88 (pricing by 0.01 increment...)
  # openrouter/google/gemini-2.5-flash                 0.30/2.50
  # openrouter/openai/gpt-4o-mini                      0.15/0.60
  # openrouter/openai/gpt-4.1 (middle priced)          2.00/8.00
  # openrouter/deepseek/deepseek-r1-0528               0.50/2.15
  # openrouter/deepseek/deepseek-chat-v3               0.38/0.89
  # openrouter/openai/gpt-4.1-mini-2025-04-14          0.40/1.60

## Set the reasoning_effort API parameter (default: not set)
#reasoning-effort: xxx

## Set the thinking token budget for models that support it (default: not set)
#thinking-tokens: xxx

## Verify the SSL cert when connecting to models (default: True)
#verify-ssl: true

## Timeout in seconds for API calls (default: None)
#timeout: xxx

## Specify what edit format the LLM should use (default depends on model)
#edit-format: xxx

## Use architect edit format for the main chat
#architect: false

## Enable/disable automatic acceptance of architect changes (default: True)
#auto-accept-architect: true

## Specify the model to use for commit messages and chat history summarization (default depends on --model)
#weak-model: xxx

## Specify the model to use for editor tasks (default depends on --model)
#editor-model: xxx

## Specify the edit format for the editor model (default: depends on editor model)
#editor-edit-format: xxx

## Only work with models that have meta-data available (default: True)
#show-model-warnings: true

## Check if model accepts settings like reasoning_effort/thinking_tokens (default: True)
#check-model-accepts-settings: true

## Soft limit on tokens for chat history, after which summarization begins. If unspecified, defaults to the model's max_chat_history_tokens.
#max-chat-history-tokens: xxx

#################
# Cache settings:

## Enable caching of prompts (default: False)
#cache-prompts: false

## Number of times to ping at 5min intervals to keep prompt cache warm (default: 0)
#cache-keepalive-pings: false

###################
# Repomap settings:

## Suggested number of tokens to use for repo map, use 0 to disable
# Context map is disabled when working from teh root: mixing GO and TS confuse the models.
map-tokens: "0"

## Control how often the repo map is refreshed. Options: auto, always, files, manual (default: auto)
#map-refresh: auto

## Multiplier for map tokens when no files are specified (default: 2)
#map-multiplier-no-files: true

###############
# Git settings:

## Only consider files in the current subtree of the git repository
subtree-only: true

## Attribute aider code changes in the git author name (default: True). If explicitly set to True, overrides --attribute-co-authored-by precedence.
#attribute-author: xxx

## Attribute aider commits in the git committer name (default: True). If explicitly set to True, overrides --attribute-co-authored-by precedence for aider edits.
#attribute-committer: xxx

## Prefix commit messages with 'aider: ' if aider authored the changes (default: False)
#attribute-commit-message-author: false

## Prefix all commit messages with 'aider: ' (default: False)
#attribute-commit-message-committer: false

## Attribute aider edits using the Co-authored-by trailer in the commit message (default: False). If True, this takes precedence over default --attribute-author and --attribute-committer behavior unless they are explicitly set to True.
#attribute-co-authored-by: false

## Enable/disable git pre-commit hooks with --no-verify (default: False)
#git-commit-verify: false

## Specify a custom prompt for generating commit messages
#commit-prompt: xxx

## Enable/disable watching files for ai coding comments (default: False)
#watch-files: false

#################
# Other settings:

## Enable/disable suggesting shell commands (default: True)
# disabled because of poor suggestions (tools used on the project are deprecated)
suggest-shell-commands: false
