services:
  localstack:
    image: localstack/localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,dynamodb,acm,ssm,sns,sqs
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - "./.build/localstack:/var/lib/localstack"
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './tools/localstack-init:/docker-entrypoint-initaws.d'

  wiremock:
    profiles: ["bg"]
    image: amazoncorretto:17-alpine
    command:
      - sh
      - -c
      # no --track: fswatch doesn't work on mounted volumes :(
      - |
        apk add --no-cache bash curl && \
        ./scripts/wiremock.sh --debug
    working_dir: /src
    ports:
      - "8080:8080"
    volumes:
      - "./:/src"
