version: '3.7'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3,dynamodb,acm,ssm
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - "./.build/localstack:/tmp/localstack"
      - '/var/run/docker.sock:/var/run/docker.sock'
