import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {getBackendSession} from "@/libs/security/session-utils";
import {UserInfo} from "../components/user-info/index.tsx/user-info";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getBackendSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {session && (
          <UserInfo
            name={session.authenticatedUser.name}
            email={session.authenticatedUser.email}
            picture={session.authenticatedUser.picture}
          />
        )}
        {children}
      </body>
    </html>
  );
}
