import "server-only"

import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {UserInfo} from "@/components/UserInfo";
import {getValidAuthentication} from "@/libs/security";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const authentication = await getValidAuthentication()

    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {authentication.status == 'authenticated' && (
            <UserInfo
                name={authentication.authenticatedUser.name}
                email={authentication.authenticatedUser.email}
                picture={authentication.authenticatedUser.picture}
                logoutUrl={authentication.logoutUrl}
            />
        )}
        {children}
        </body>
        </html>
    );
}
