import "server-only"

import type {Metadata} from "next";
import {getCurrentAuthentication} from "@/libs/security";
import {newReadCookieStoreFromComponents} from "@/libs/nextjs-cookies";
import AppLayout from "@/components/AppLayout";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const authentication = await getCurrentAuthentication(await newReadCookieStoreFromComponents())

    if (authentication.status !== 'authenticated') {
        return <>{children}</>;
    }

    return (
        <AppLayout user={authentication.authenticatedUser} logoutUrl={authentication.logoutUrl}>
            {children}
        </AppLayout>
    );
}
