import "server-only"

import type {Metadata} from "next";
import {UserInfo} from "@/components/UserInfo";
import {getValidAuthentication} from "@/libs/security";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const authentication = await getValidAuthentication()

    return (
        <>
            {authentication.status == 'authenticated' && (
                <UserInfo
                    name={authentication.authenticatedUser.name}
                    email={authentication.authenticatedUser.email}
                    picture={authentication.authenticatedUser.picture}
                    logoutUrl={authentication.logoutUrl}
                />
            )}
            {children}
        </>
    );
}
