name: 'Setup Golang'
description: 'Setup Go and any caching required for this project'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - id: go-cache-paths
      shell: 'bash'
      run: |
        echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT

    - name: Build Cache (and test)
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}-v2
