name: 'Install GO'
description: 'Setup Go and any caching required for this project'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.17.8'

    - id: go-cache-paths
      shell: 'sh'
      run: |
        echo "::set-output name=go-build::$(go env GOCACHE)"
        echo "::set-output name=go-mod::$(go env GOMODCACHE)"

    - name: Go Build Cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.go-cache-paths.outputs.go-build }}
          ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-deps-${{ hashFiles('**/go.sum') }}