name: 'Install GO'
description: 'Setup Go and any caching required for this project'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

#    - id: go-cache-paths
#      shell: 'sh'
#      run: |
#        echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
#        echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
#
#    - name: Go Build Cache
#      uses: actions/cache@v4
#      with:
#        path: |
#          ${{ steps.go-cache-paths.outputs.go-build }}
#          ${{ steps.go-cache-paths.outputs.go-mod }}
#        key: ${{ runner.os }}-go-deps-${{ hashFiles('**/go.sum') }}
