// Code generated by mockery v2.3.0. DO NOT EDIT.

package backup

import mock "github.com/stretchr/testify/mock"

// MockTrackAnalysed is an autogenerated mock type for the TrackAnalysed type
type MockTrackAnalysed struct {
	mock.Mock
}

// OnAnalysed provides a mock function with given fields: done, total
func (_m *MockTrackAnalysed) OnAnalysed(done MediaCounter, total MediaCounter) {
	_m.Called(done, total)
}
