// Code generated by mockery v2.3.0. DO NOT EDIT.

package backup

import mock "github.com/stretchr/testify/mock"

// MockTrackUploaded is an autogenerated mock type for the TrackUploaded type
type MockTrackUploaded struct {
	mock.Mock
}

// OnUploaded provides a mock function with given fields: done, total
func (_m *MockTrackUploaded) OnUploaded(done MediaCounter, total MediaCounter) {
	_m.Called(done, total)
}
