// Code generated by mockery v2.3.0. DO NOT EDIT.

package backup

import (
	model "duchatelle.io/dphoto/dphoto/backup/model"
	mock "github.com/stretchr/testify/mock"
)

// MockMediaScannerAdapter is an autogenerated mock type for the MediaScannerAdapter type
type MockMediaScannerAdapter struct {
	mock.Mock
}

// FindMediaRecursively provides a mock function with given fields: volume, paths
func (_m *MockMediaScannerAdapter) FindMediaRecursively(volume model.VolumeToBackup, paths chan model.FoundMedia) error {
	ret := _m.Called(volume, paths)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.VolumeToBackup, chan model.FoundMedia) error); ok {
		r0 = rf(volume, paths)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
