// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package backup

import mock "github.com/stretchr/testify/mock"

// MockFileHandlerAdapter is an autogenerated mock type for the FileHandlerAdapter type
type MockFileHandlerAdapter struct {
	mock.Mock
}

// CopyToLocal provides a mock function with given fields: originPath, destPath
func (_m *MockFileHandlerAdapter) CopyToLocal(originPath string, destPath string) (string, error) {
	ret := _m.Called(originPath, destPath)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(originPath, destPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(originPath, destPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMediaRecursively provides a mock function with given fields: mountPath, paths
func (_m *MockFileHandlerAdapter) FindMediaRecursively(mountPath string, paths chan FoundMedia) error {
	ret := _m.Called(mountPath, paths)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, chan FoundMedia) error); ok {
		r0 = rf(mountPath, paths)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
