// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package backup

import mock "github.com/stretchr/testify/mock"

// MockImageDetailsReaderAdapter is an autogenerated mock type for the ImageDetailsReaderAdapter type
type MockImageDetailsReaderAdapter struct {
	mock.Mock
}

// ReadImageDetails provides a mock function with given fields: imagePath
func (_m *MockImageDetailsReaderAdapter) ReadImageDetails(imagePath string) (*MediaDetails, error) {
	ret := _m.Called(imagePath)

	var r0 *MediaDetails
	if rf, ok := ret.Get(0).(func(string) *MediaDetails); ok {
		r0 = rf(imagePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MediaDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(imagePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
