// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package backup

import mock "github.com/stretchr/testify/mock"

// MockOnlineStorageAdapter is an autogenerated mock type for the OnlineStorageAdapter type
type MockOnlineStorageAdapter struct {
	mock.Mock
}

// BackupOnline provides a mock function with given fields: mediaChannel
func (_m *MockOnlineStorageAdapter) BackupOnline(mediaChannel chan LocalMedia) error {
	ret := _m.Called(mediaChannel)

	var r0 error
	if rf, ok := ret.Get(0).(func(chan LocalMedia) error); ok {
		r0 = rf(mediaChannel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
