// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// analyseProgressListener is an autogenerated mock type for the analyseProgressListener type
type analyseProgressListener struct {
	mock.Mock
}

// OnAnalyseProgress provides a mock function with given fields: count, total
func (_m *analyseProgressListener) OnAnalyseProgress(count uint, total uint) {
	_m.Called(count, total)
}
