// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	backup "github.com/thomasduchatelle/dphoto/domain/backup"

	testing "testing"
)

// ArchiveAdapter is an autogenerated mock type for the ArchiveAdapter type
type ArchiveAdapter struct {
	mock.Mock
}

// ArchiveMedia provides a mock function with given fields: owner, media
func (_m *ArchiveAdapter) ArchiveMedia(owner string, media *backup.BackingUpMediaRequest) (string, error) {
	ret := _m.Called(owner, media)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, *backup.BackingUpMediaRequest) string); ok {
		r0 = rf(owner, media)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *backup.BackingUpMediaRequest) error); ok {
		r1 = rf(owner, media)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewArchiveAdapter creates a new instance of ArchiveAdapter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewArchiveAdapter(t testing.TB) *ArchiveAdapter {
	mock := &ArchiveAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
