// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	backupmodel "github.com/thomasduchatelle/dphoto/dphoto/backup/backupmodel"

	testing "testing"
)

// Filter is an autogenerated mock type for the Filter type
type Filter struct {
	mock.Mock
}

// Execute provides a mock function with given fields: found
func (_m *Filter) Execute(found backupmodel.FoundMedia) bool {
	ret := _m.Called(found)

	var r0 bool
	if rf, ok := ret.Get(0).(func(backupmodel.FoundMedia) bool); ok {
		r0 = rf(found)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewFilter creates a new instance of Filter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewFilter(t testing.TB) *Filter {
	mock := &Filter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
