// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	config "github.com/thomasduchatelle/dphoto/dphoto/config"

	testing "testing"
)

// Listener is an autogenerated mock type for the Listener type
type Listener struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Listener) Execute(_a0 config.Config) {
	_m.Called(_a0)
}

// NewListener creates a new instance of Listener. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewListener(t testing.TB) *Listener {
	mock := &Listener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
