// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	config "github.com/thomasduchatelle/dphoto/dphoto/config"
)

// Listener is an autogenerated mock type for the Listener type
type Listener struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *Listener) Execute(_a0 config.Config) {
	_m.Called(_a0)
}
