// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	backupmodel "github.com/thomasduchatelle/dphoto/dphoto/backup/backupmodel"

	testing "testing"
)

// PostAnalyseFilter is an autogenerated mock type for the PostAnalyseFilter type
type PostAnalyseFilter struct {
	mock.Mock
}

// AcceptAnalysedMedia provides a mock function with given fields: media, folderName
func (_m *PostAnalyseFilter) AcceptAnalysedMedia(media *backupmodel.AnalysedMedia, folderName string) bool {
	ret := _m.Called(media, folderName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*backupmodel.AnalysedMedia, string) bool); ok {
		r0 = rf(media, folderName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewPostAnalyseFilter creates a new instance of PostAnalyseFilter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPostAnalyseFilter(t testing.TB) *PostAnalyseFilter {
	mock := &PostAnalyseFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
