// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	backupmodel "github.com/thomasduchatelle/dphoto/dphoto/backup/backupmodel"
)

// PostAnalyseFilter is an autogenerated mock type for the PostAnalyseFilter type
type PostAnalyseFilter struct {
	mock.Mock
}

// AcceptAnalysedMedia provides a mock function with given fields: media, folderName
func (_m *PostAnalyseFilter) AcceptAnalysedMedia(media *backupmodel.AnalysedMedia, folderName string) bool {
	ret := _m.Called(media, folderName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*backupmodel.AnalysedMedia, string) bool); ok {
		r0 = rf(media, folderName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
