// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// scanCompleteListener is an autogenerated mock type for the scanCompleteListener type
type scanCompleteListener struct {
	mock.Mock
}

// OnScanComplete provides a mock function with given fields: total
func (_m *scanCompleteListener) OnScanComplete(total uint) {
	_m.Called(total)
}

// newScanCompleteListener creates a new instance of scanCompleteListener. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func newScanCompleteListener(t testing.TB) *scanCompleteListener {
	mock := &scanCompleteListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
