// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	backup "github.com/thomasduchatelle/dphoto/domain/backup"

	testing "testing"
)

// TrackEvents is an autogenerated mock type for the TrackEvents type
type TrackEvents struct {
	mock.Mock
}

// OnEvent provides a mock function with given fields: event
func (_m *TrackEvents) OnEvent(event backup.ProgressEvent) {
	_m.Called(event)
}

// NewTrackEvents creates a new instance of TrackEvents. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewTrackEvents(t testing.TB) *TrackEvents {
	mock := &TrackEvents{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
