// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// UpdateAlbumPort is an autogenerated mock type for the UpdateAlbumPort type
type UpdateAlbumPort struct {
	mock.Mock
}

// UpdateAlbum provides a mock function with given fields: folderName, start, end
func (_m *UpdateAlbumPort) UpdateAlbum(folderName string, start time.Time, end time.Time) error {
	ret := _m.Called(folderName, start, end)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) error); ok {
		r0 = rf(folderName, start, end)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
