// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	oauthmodel "github.com/thomasduchatelle/dphoto/domain/oauthmodel"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// FindUserRoles provides a mock function with given fields: email
func (_m *UserRepository) FindUserRoles(email string) (*oauthmodel.UserRoles, error) {
	ret := _m.Called(email)

	var r0 *oauthmodel.UserRoles
	if rf, ok := ret.Get(0).(func(string) *oauthmodel.UserRoles); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauthmodel.UserRoles)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
