// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// UserInputPort is an autogenerated mock type for the UserInputPort type
type UserInputPort struct {
	mock.Mock
}

// StartListening provides a mock function with given fields:
func (_m *UserInputPort) StartListening() {
	_m.Called()
}

// NewUserInputPort creates a new instance of UserInputPort. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserInputPort(t testing.TB) *UserInputPort {
	mock := &UserInputPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
