// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	backupmodel "github.com/thomasduchatelle/dphoto/dphoto/backup/backupmodel"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// VolumeManagerPort is an autogenerated mock type for the VolumeManagerPort type
type VolumeManagerPort struct {
	mock.Mock
}

// OnMountedVolume provides a mock function with given fields: volume
func (_m *VolumeManagerPort) OnMountedVolume(volume backupmodel.VolumeToBackup) {
	_m.Called(volume)
}

// OnUnMountedVolume provides a mock function with given fields: uuid
func (_m *VolumeManagerPort) OnUnMountedVolume(uuid string) {
	_m.Called(uuid)
}

// NewVolumeManagerPort creates a new instance of VolumeManagerPort. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewVolumeManagerPort(t testing.TB) *VolumeManagerPort {
	mock := &VolumeManagerPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
