// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	ui "github.com/thomasduchatelle/dphoto/dphoto/cmd/ui"
	mock "github.com/stretchr/testify/mock"
)

// CreateAlbumPort is an autogenerated mock type for the CreateAlbumPort type
type CreateAlbumPort struct {
	mock.Mock
}

// Create provides a mock function with given fields: createRequest
func (_m *CreateAlbumPort) Create(createRequest ui.RecordCreation) error {
	ret := _m.Called(createRequest)

	var r0 error
	if rf, ok := ret.Get(0).(func(ui.RecordCreation) error); ok {
		r0 = rf(createRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
