// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	io "io"

	backupmodel "github.com/thomasduchatelle/dphoto/dphoto/backup/backupmodel"

	mock "github.com/stretchr/testify/mock"
)

// DetailsReaderAdapter is an autogenerated mock type for the DetailsReaderAdapter type
type DetailsReaderAdapter struct {
	mock.Mock
}

// ReadDetails provides a mock function with given fields: reader, options
func (_m *DetailsReaderAdapter) ReadDetails(reader io.Reader, options backupmodel.DetailsReaderOptions) (*backupmodel.MediaDetails, error) {
	ret := _m.Called(reader, options)

	var r0 *backupmodel.MediaDetails
	if rf, ok := ret.Get(0).(func(io.Reader, backupmodel.DetailsReaderOptions) *backupmodel.MediaDetails); ok {
		r0 = rf(reader, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backupmodel.MediaDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.Reader, backupmodel.DetailsReaderOptions) error); ok {
		r1 = rf(reader, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Supports provides a mock function with given fields: media, mediaType
func (_m *DetailsReaderAdapter) Supports(media backupmodel.FoundMedia, mediaType backupmodel.MediaType) bool {
	ret := _m.Called(media, mediaType)

	var r0 bool
	if rf, ok := ret.Get(0).(func(backupmodel.FoundMedia, backupmodel.MediaType) bool); ok {
		r0 = rf(media, mediaType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
