// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	backupmodel "github.com/thomasduchatelle/dphoto/dphoto/backup/backupmodel"
	mock "github.com/stretchr/testify/mock"
)

// Downloader is an autogenerated mock type for the Downloader type
type Downloader struct {
	mock.Mock
}

// Execute provides a mock function with given fields: found
func (_m *Downloader) Execute(found backupmodel.FoundMedia) (backupmodel.FoundMedia, error) {
	ret := _m.Called(found)

	var r0 backupmodel.FoundMedia
	if rf, ok := ret.Get(0).(func(backupmodel.FoundMedia) backupmodel.FoundMedia); ok {
		r0 = rf(found)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(backupmodel.FoundMedia)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(backupmodel.FoundMedia) error); ok {
		r1 = rf(found)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
