// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import (
	backupmodel "github.com/thomasduchatelle/dphoto/dphoto/backup/backupmodel"
	mock "github.com/stretchr/testify/mock"
)

// TrackDownloaded is an autogenerated mock type for the TrackDownloaded type
type TrackDownloaded struct {
	mock.Mock
}

// OnDownloaded provides a mock function with given fields: done, total
func (_m *TrackDownloaded) OnDownloaded(done backupmodel.MediaCounter, total backupmodel.MediaCounter) {
	_m.Called(done, total)
}
