// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserInputPort is an autogenerated mock type for the UserInputPort type
type UserInputPort struct {
	mock.Mock
}

// StartListening provides a mock function with given fields:
func (_m *UserInputPort) StartListening() {
	_m.Called()
}
