name: 'Install terraform'
description: 'Uses .terraform-version to choose the right terraform version.'
runs:
  using: "composite"
  steps:
    - name: Get terraform version
      id: vars
      run: echo "::set-output name=terraform-version::$(cat infra-data/.terraform-version)"
      shell: sh
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ steps.vars.output.terraform-version }}
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
