name: 'Setup AWS CDK'
description: 'Setup Node.js and install AWS CDK CLI and dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '^22.0.0'
        cache: 'npm'
        cache-dependency-path: deployments/cdk/package-lock.json

    - name: Install CDK dependencies
      working-directory: deployments/cdk
      shell: bash
      run: npm ci

    - name: Install AWS CDK CLI
      shell: bash
      run: npm install -g aws-cdk
