name: 'Setup AWS CDK and SST'
description: 'Setup Node.js and install AWS CDK CLI, SST, and dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '^24'

    - name: Cache SST platform
      uses: actions/cache@v4
      with:
        path: |
          deployments/cdk/node_modules
          deployments/cdk/.sst/cache
        key: ${{ runner.os }}-sst-cache-${{ hashFiles('deployments/cdk/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-sst-cache-

    - name: NPM install & SST install
      working-directory: deployments/cdk
      shell: bash
      run: |
        npm ci
        npx sst install
        node ../../scripts/pulumi-patch.js || echo "FAILED to patch pulumi"
        npm install -g aws-cdk

    # Workaround for Pulumi version conflict:
    # GitHub runners have Pulumi 3.212.0+ pre-installed, which removed the -root flag
    # from pulumi-language-nodejs (see https://github.com/pulumi/pulumi/pull/21065).
    # SST 3.17.x uses Pulumi SDK 3.210.0 which still passes -root, causing a conflict.
    # Removing the system language plugin forces SST to use its bundled compatible version.
    - name: Fix Pulumi version conflict
      shell: bash
      run: sudo rm -f /usr/local/bin/pulumi-language-nodejs
