name: 'Setup AWS CDK and SST'
description: 'Setup Node.js and install AWS CDK CLI, SST, and dependencies'
inputs:
  install-sst:
    description: 'Whether to install SST platform (default: false)'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '^24'
        cache: 'npm'
        cache-dependency-path: deployments/cdk/package-lock.json

    - name: Cache SST platform
      if: ${{ inputs.install-sst == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          deployments/cdk/.sst/cache
        key: ${{ runner.os }}-sst-cache-${{ hashFiles('deployments/cdk/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-sst-cache-

    - name: Install CDK dependencies
      working-directory: deployments/cdk
      shell: bash
      run: npm ci

    - name: Install AWS CDK CLI
      shell: bash
      run: npm install -g aws-cdk

    - name: Install SST
      if: ${{ inputs.install-sst == 'true' }}
      working-directory: deployments/cdk
      shell: bash
      run: |
        npx sst install
        node ../../scripts/pulumi-patch.js || echo "FAILED to patch pulumi"
