name: 'NodeJS Setup'
description: 'Run npm install and yarn install everywhere required and cache node_modules'
inputs:
  sls:
    description: install globally serverless cli
    required: false
    default: 'false'
  cache-suffix:
    description: Suffix to add to the cache key (cache has a tendency to be locked otherwise)
    required: false
    default: '0.1'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '19'
        # cache: yarn # note - directly caching node_modules is MUCH faster (60s -> 1.5s)
    - name: YARN Cache (restore)
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.npm
          web/node_modules
          deployments/sls/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('web/yarn.lock', 'deployments/sls/yarn.lock') }}-${{ inputs.cache-suffix }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('web/yarn.lock', 'deployments/sls/yarn.lock') }}
    - name: Download deps
      if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
      run: make setup-app
      shell: bash
    - name: Install SLS
      if: ${{ inputs.sls == 'true' }}
      run: npm install -g serverless
      shell: bash
    - name: YARN Cache (always save)
      if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.npm
          web/node_modules
          deployments/sls/node_modules
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
