name: 'Puppeteer Run'
description: 'Run in a container where chrome and puppeteer is controlled and reproducible locally'
#inputs:
#  yarn:
#    description: 'YARN arguments'
#    required: true
#    default: ''
runs:
  using: 'docker'
  image: '../../../tools/puppeteer/Dockerfile'
  args:
    - sh
    - "-c"
    - cd web && yarn ${{ inputs.who-to-greet }}