name: Feature branch continuous integration
on:
  push:
    branches-ignore:
      - next
      - main
      - actions
      - update-snapshots
#  pull_request:
#    branches:
#      - main
#      - next

jobs:
  update-snapshots:
    timeout-minutes: 10
    if: ${{ contains(github.event.head_commit.message, '+update-snapshots') }}
    runs-on: ubuntu-latest
    outputs:
      skip_downstream: ${{ steps.auto-commit.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_AUTO_COMMIT }}

      - name: Setup NODE
        uses: ./.github/actions/install-node
      - name: Generate snapshots
        run: make update-snapshots

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit
        with:
          commit_message: "web/* - update visual regression snapshots using CI machines."

  semver:
    name: "Next Semantic Version"
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semver.outputs.MajorMinorPatch }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: semver
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true

  test-go-code:
    runs-on: ubuntu-latest
#    if: ${{ always() && !needs.update-snapshots.outputs.skip_downstream }}
    if: ${{ success() && needs.update-snapshots.outputs.skip_downstream == 'false' || !cancelled() && needs.update-snapshots.result == 'skipped' }}
    needs:
      - update-snapshots
    steps:
      - uses: actions/checkout@v4
      - name: Setup GO
        uses: ./.github/actions/install-go
      - name: start mock services
        run: docker-compose up -d
      - run: make test-go

  test-ts-code:
    runs-on: ubuntu-latest
#    if: ${{ always() && !needs.update-snapshots.outputs.skip_downstream }}
    if: ${{ success() || ! (cancelled() && needs.update-snapshots.result == 'cancelled') }}
    needs:
      - update-snapshots
    steps:
      - uses: actions/checkout@v4

      - name: Setup NODE
        uses: ./.github/actions/install-node
      - name: Test and build WEB UI
        run: make test-web build-web
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: storybook-snapshots
          path: web/src/stories/__image_snapshots__/__diff_output__/
