on:
  push:
    branches:
      - develop

jobs:
  provision-data-infrastructure:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: dev
    env:
      TF_WORKSPACE: dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup terraform
        uses: ./.github/actions/install-terraform
        with:
          tf-api-token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        id: init
        run: cd infra-data && terraform init

      - name: Terraform apply
        run: cd infra-data && terraform apply -auto-approve

  deploy-app:
    runs-on: ubuntu-latest
    environment: dev
    needs: [provision-data-infrastructure]
    env:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v3
      - name: Setup GO
        uses: ./.github/actions/install-go
      - name: Setup NODE
        uses: ./.github/actions/install-node

      - name: Build and deploy
        run: make deploy-app


