name: Feature branch continuous integration
on: [ push ]
jobs:
  test-go-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17.8'

      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - name: Go Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-cache-paths.outputs.go-build }}
            ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-deps-${{ hashFiles('**/go.sum') }}

      - name: start mock services
        run: docker-compose up -d
      - run: make test-domain test-app-api test-cli

  test-ts-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
          # note - directly caching node_modules is MUCH faster
      - name: YARN and NPM Cache
        uses: actions/cache@v3
        with:
          path: |
            app/viewer_ui/node_modules
            app/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('app/viewer_ui/yarn.lock', 'app/package-lock.json') }}
      - name: Test and build WEB UI
        run: make install-app test-app-ui build-app-ui
