name: Feature branch continuous integration
on:
  push:
    branches-ignore:
      - next
      - main
      - actions
  workflow_call:

jobs:
#  test-go-code:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup GO
#        uses: ./.github/actions/install-go
#      - name: start mock services
#        run: docker-compose up -d
#      - run: make test-go

  test-ts-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NODE
        uses: ./.github/actions/install-node
#      - name: Test and build WEB UI
#        uses: ./.github/actions/puppeteer
#        with:
#          yarn: test:ci
#      - name: Test and build WEB UI
#        run: make test-web build-web
      - name: Create baseline
        run: cd web && yarn && yarn build-storybook && CI=true yarn test
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: storybook-snapshots
          path: web/src/stories/__image_snapshots__/