name: test-cdk

on:
  workflow_call:
    inputs:
      cache-suffix:
        description: "Suffix to add to the cache key"
        type: string
        default: "0.1"

jobs:
  cdk-validation:
    name: test-cdk
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CDK
        uses: ./.github/actions/install-cdk

      - name: Run CDK tests
        run: make test-cdk
