name: CDK Diff Comment Job

on:
  workflow_call:
    inputs:
      issue-number:
        description: "The issue number on which the comment is posted"
        required: true
        type: string
      cache-suffix:
        description: "Suffix to add to the cache key"
        type: string
        default: "0.1"

jobs:
  cdk-diff-comment:
    runs-on: ubuntu-latest
    environment:
      name: live
    steps:
      - uses: actions/checkout@v4

      - name: Setup CDK
        uses: ./.github/actions/install-cdk

      - name: Download api
        uses: actions/download-artifact@v4
        with:
          name: dist-api
          path: bin

      - name: Download web
        uses: actions/download-artifact@v4
        with:
          name: dist-web
          path: web/dist

      - name: Download waku
        uses: actions/download-artifact@v4
        with:
          name: dist-waku
          path: web-waku/dist

      - name: CDK Diff (live)
        id: diff
        working-directory: deployments/cdk
        run: |
          set +e  # Don't exit on command failure
          cdk diff --context environment=live --no-color > diff_output.txt 2>&1
          RC=$?
          
          cat diff_output.txt
          
          if [[ $RC -ne 0 ]]; then
            echo "CDK diff failed with exit code $RC"
            exit $RC
          fi
          
          # Check if there are actual changes in the output
          if grep -q "Stack.*" diff_output.txt; then
            if grep -qE "([\+\-\~]|\[[\+\-\~]]|Resources|Parameters|Outputs)" diff_output.txt; then
              echo "no_change=false" >> $GITHUB_OUTPUT
            else
              echo "no_change=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "no_change=true" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

      - name: Update Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const diffOutput = fs.readFileSync('deployments/cdk/diff_output.txt', 'utf8');
            
            let summary = "";
            if ('${{ steps.diff.outputs.no_change }}' === 'true') {
              summary = " - no change"
            }
            
            const output = `### CDK live

            <details><summary>Show Diff${summary}</summary>

            \`\`\`
            ${diffOutput}
            \`\`\`

            </details>

            *Action: \`${{ github.event_name }}\`*`;
            
            const issueNumber = "${{ inputs.issue-number }}"

            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Report failure (or skip)
        if: contains(steps.*.outcome, 'failure')
        run: exit 1