on:
  workflow_call:
    inputs: {}

jobs:
  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    outputs:
      pr-created: ${{ steps.pr.outputs.result != '' && 'true' || 'false' }}
      pr-number: ${{ steps.pr.outputs.result }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: SemVer
        id: semver
        uses: ./.github/actions/semver

      - name: Changelog
        id: changelog
        uses: ./.github/actions/generate-changelog
        with:
          version: ${{ steps.semver.outputs.version }}

      - name: Create or Update PR
        id: pr
        uses: actions/github-script@v7
        env:
          TITLE: ${{ steps.changelog.outputs.title-with-version }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'thomasduchatelle:${{ github.ref_name }}'
            });

            const title = process.env.TITLE
            const body = process.env.CHANGELOG

            if (prs.status !== 200) {
              console.log("error fetching exiting PRs: " + JSON.stringify(prs))

            } else if (prs.data.length == 0) {
              console.log("Creating a PR for ${{ github.ref }}");
              const created = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: 'thomasduchatelle:${{ github.ref_name }}',
                base: 'main',
                title: title,
                body: body,
              });

              if (created.status == 201) {
                console.log("PR '"+ created.data.number + "' has been created");
                return created.data.number
              } else {
                console.log("Error when creating the PR: " + JSON.stringify(created));
                return
              }
            }

            const pr = prs.data[0]

            if (('${{ contains(github.event.head_commit.message, '+pr') }}' === 'true' || '${{ contains(github.event.head_commit.message, '+next') }}' === 'true') &&
              (pr.title !== title || pr.body !== body)
              ) {
              console.log("PR " + pr.number + " will be updated ...")
              console.log("Old title -> " + pr.title)
              console.log("New title -> " + title)
              console.log("Old body -> " + pr.body)
              console.log("New body -> " + body)

              github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                title: title,
                body: body,
              });

            } else {
              console.log("PR not updated, match = " + (pr.title !== title || pr.body !== body) + " ; +pr = ${{ contains(github.event.head_commit.message, '+pr') }}")
            }

            return ""

  tf-plan-live:
    name: "Comment live plan on PR"
    needs:
      - pull-request
    if: ${{ success() && needs.pull-request.outputs.pr-created == 'true' }}
    uses: ./.github/workflows/workflow-pull-request.yml
    secrets: inherit
    with:
      issue-number: ${{ needs.pull-request.outputs.pr-number }}