on:
  workflow_call:
    inputs:
      ref:
        description: "Git ref to checkout (branch, tag, or SHA)"
        type: string
        required: false
    outputs:
      cache-suffix:
        description: Typescript cache suffix
        value: ${{ jobs.build-ts.outputs.cache-suffix }}

jobs:
  build-ts:
    runs-on: ubuntu-latest
    outputs:
      cache-suffix: ${{ steps.semver.outputs.cache-suffix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ inputs.ref || github.head_ref }}
      - name: SemVer
        id: semver
        uses: ./.github/actions/semver

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            web/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ hashFiles('web/package-lock.json') }}

      - name: Setup NodeJS
        uses: ./.github/actions/install-node
        with:
          cache-suffix: ${{ steps.semver.outputs.cache-suffix }}

      - name: Build for release
        run: make build-web

      - name: Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-web
          path: |
            web/dist/**
