name: CDK Validation Job

on:
  workflow_call:
    inputs:
      cache-suffix:
        description: "Suffix to add to the cache key"
        type: string
        default: "0.1"

jobs:
  cdk-validation:
    name: CDK Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: deployments/cdk/package-lock.json

      - name: Install CDK dependencies
        working-directory: deployments/cdk
        run: npm ci

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: CDK Syntax Check (dev)
        working-directory: deployments/cdk
        run: cdk synth --context environment=dev

      - name: CDK Syntax Check (live)
        working-directory: deployments/cdk
        run: cdk synth --context environment=live

      - name: Run CDK unit tests
        working-directory: deployments/cdk
        run: npm test

      - name: CDK diff (dev) - if AWS credentials available
        working-directory: deployments/cdk
        run: cdk diff --context environment=dev || echo "No AWS credentials - skipping diff"
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1