name: CDK PR Plan Job

on:
  workflow_call:
    inputs:
      issue-number:
        description: "Override the issue number on which the comment is posted"
        required: false
        type: string

jobs:
  cdk-pr-plan:
    runs-on: ubuntu-latest
    environment:
      name: live
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: deployments/cdk/package-lock.json

      - name: Install CDK dependencies
        working-directory: deployments/cdk
        run: npm ci

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: CDK Diff (live)
        id: diff
        working-directory: deployments/cdk
        run: |
          RC=0
          cdk diff --context environment=live --no-color || RC=$?
          
          if [[ $RC -eq 0 ]] ; then
            echo "no_change=true" >> $GITHUB_OUTPUT
          else
            if [[ $RC -eq 1 ]] ; then 
              echo "no_change=false" >> $GITHUB_OUTPUT
            else
              exit $RC
            fi
          fi
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Update Pull Request
        uses: actions/github-script@v7
        env:
          DIFF: "cdk\n${{ steps.diff.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let summary = "";
            if ('${{ steps.diff.outputs.no_change }}' === 'true' ) {
              summary = " - no change"
            }
            
            const output = `### CDK live

            <details><summary>Show Diff${summary}</summary>

            \`\`\`\n
            ${process.env.DIFF}
            \`\`\`

            </details>

            *Action: \`${{ github.event_name }}\`*`;
            
            const issueNumber = "${{ github.event_name }}" === "pull_request" ? context.issue.number : "${{ inputs.issue-number }}"

            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: CDK Diff Status
        if: contains(steps.*.outcome, 'failure')
        run: exit 1