name: Feature branch continuous integration
on:
  workflow_call:
    inputs:
      ref:
        description: branch name (github.base_ref for pull requests, and github.ref_name for pushes)
        required: true
        type: string
    outputs:
      environment-name:
        value: ${{ jobs.choose-env.outputs.environment-name }}
      environment-workspace:
        value: ${{ jobs.choose-env.outputs.environment-workspace }}

jobs:
  choose-env:
    runs-on: ubuntu-latest
    outputs:
      environment-name: ${{ steps.setenv.outputs.environment-name }}
      environment-workspace: ${{ steps.setenv.outputs.environment-workspace }}
    steps:
      - name: set environment based on the branch
        id: setenv
        run: |
          case "${{ inputs.ref }}" in
            "main")
              echo "environment-name=live" >> $GITHUB_OUTPUT
              echo "environment-workspace=live" >> $GITHUB_OUTPUT
              ;;
          
            "next")
              echo "environment-name=dev" >> $GITHUB_OUTPUT 
              echo "environment-workspace=dev" >> $GITHUB_OUTPUT
              ;;
          
            *)
              echo "Reference is not set to use any environment"
              exit 1
              ;;
          esac
