on:
  pull_request:
    branches:
      - main
      - next

jobs:
  choose-env:
    uses: ./.github/workflows/lib-choose-environment.yml
    with:
      ref: ${{ github.base_ref }}

  post-terraform-plan:
    name: post-terraform-plan-${{ needs.choose-env.outputs.environment-name }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.choose-env.outputs.environment-name }}
    needs:
      - choose-env
    env:
      TF_WORKSPACE: ${{ needs.choose-env.outputs.environment-workspace }}
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "Env name: ${{ needs.choose-env.outputs.environment-name }}"
          echo "Env workspace: ${{ needs.jobs.choose-env.outputs.environment-workspace }}"

      - name: Setup terraform
        uses: ./.github/actions/install-terraform
        with:
          tf-api-token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        id: init
        run: cd deployments/infra-data && terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run:  |
          cd deployments/infra-data
          RC=0
          terraform plan -no-color || RC=$?

          if [[ $RC -eq 0 ]] ; then
           echo "no_change=true" >> $GITHUB_OUTPUT
          else
            if [[ $RC -eq 2 ]] ; then 
              echo "no_change=false" >> $GITHUB_OUTPUT
            else
              return $RC
            fi
          fi
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let summary = "";
            if ('${{ steps.plan.outputs.no_change }}' === 'true' ) {
              summary = " - no change"
            }
            
            const output = `### ${{ needs.choose-env.outputs.environment-name }}

            <details><summary>Show Plan${summary}</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: contains(steps.*.outcome, 'failure')
        run: exit 1
