on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    uses: ./.github/workflows/feature-branch-ci.yml

  provision-data-infrastructure:
    runs-on: ubuntu-latest
    environment: dev
    needs: [tests]
    env:
      TF_WORKSPACE: dev
    steps:
      - uses: actions/checkout@v3

      - name: Get terraform version
        id: vars
        run: echo "::set-output name=terraform-version::$(cat infra-data/.terraform-version)"
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: $({ steps.vars.output.terraform-version })
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        id: init
        run: cd infra-data && terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: cd infra-data && terraform plan -no-color
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
