name: Feature CI
on:
  push:
    branches-ignore:
      - next
      - main
      - actions
      - update-snapshots

jobs:
  pull-request:
    uses: ./.github/workflows/job-pull-request.yml
    if: ${{ contains(github.event.head_commit.message, '+pr') || contains(github.event.head_commit.message, '+next') }}
    secrets: inherit

  test-go:
    uses: ./.github/workflows/job-test-go.yml
  test-ts:
    uses: ./.github/workflows/job-test-ts.yml
  test-terraform:
    uses: ./.github/workflows/job-test-terraform.yml
    secrets: inherit
    with:
      summary: ${{ contains(github.event.head_commit.message, '+next') && 'false' || 'true' }}

  test-cdk:
    uses: ./.github/workflows/job-test-cdk.yml
    with:
      cache-suffix: ${{ github.run_number }}

  build-go:
    uses: ./.github/workflows/job-build-go.yml
    if: ${{ contains(github.event.head_commit.message, '+next') }}
    with:
      snapshot: "true"
  build-ts:
    uses: ./.github/workflows/job-build-ts.yml
    if: ${{ contains(github.event.head_commit.message, '+next') }}

  deploy-dev:
    uses: ./.github/workflows/job-deploy.yml
    if: ${{ contains(github.event.head_commit.message, '+next') }}
    needs:
      - test-go
      - test-ts
      - test-terraform
      - test-cdk
      - build-go
      - build-ts
    secrets: inherit
    with:
      target: next
      skip-terraform: ${{ needs.test-terraform.outputs.no-change }}
      cache-suffix: ${{ needs.build-ts.outputs.cache-suffix }}