name: Feature CI
on:
  push:
    branches-ignore:
      - next
      - main
      - actions
      - update-snapshots

jobs:
  pull-request:
    uses: ./.github/workflows/job-pull-request.yml
    if: ${{ contains(github.event.head_commit.message, '+pr') || contains(github.event.head_commit.message, '+next') }}
    secrets: inherit

  test-go:
    uses: ./.github/workflows/job-test-go.yml
  test-ts:
    uses: ./.github/workflows/job-test-ts.yml
  test-cdk:
    uses: ./.github/workflows/job-test-cdk.yml
    with:
      cache-suffix: ${{ github.run_number }}

  build-go:
    uses: ./.github/workflows/job-build-go.yml
    if: ${{ contains(github.event.head_commit.message, '+next') }}
    with:
      snapshot: "true"
  build-ts:
    uses: ./.github/workflows/job-build-ts.yml
    if: ${{ contains(github.event.head_commit.message, '+next') }}

  deploy-next:
    uses: ./.github/workflows/job-deploy.yml
    if: ${{ contains(github.event.head_commit.message, '+next') }}
    needs:
      - test-go
      - test-ts
      - test-cdk
      - build-go
      - build-ts
    secrets: inherit
    with:
      target: next
      cache-suffix: ${{ needs.build-ts.outputs.cache-suffix }}

  comment-cdk-diff:
    uses: ./.github/workflows/job-comment-cdk-diff.yml
    if: ${{ needs.pull-request.outputs.pr-created == 'true' && (contains(github.event.head_commit.message, '+next') || contains(github.event.head_commit.message, '+pr')) }}
    needs:
      - pull-request
      - build-go
      - build-ts
    secrets: inherit
    with:
      issue-number: ${{ needs.pull-request.outputs.pr-number }}
      cache-suffix: ${{ needs.build-ts.outputs.cache-suffix }}
