name: Feature CI/CD
on:
  push:
    branches-ignore:
      - next
      - main
      - actions
      - update-snapshots

jobs:
  semver:
    uses: ./.github/workflows/lib-semver.yml

  test-build-web:
    uses: ./.github/workflows/lib-test-build-web.yml
    needs:
      - semver
    with:
      version: ${{ needs.semver.outputs.version }}
      snapshot: ${{ needs.semver.outputs.snapshot }}
      build-disabled: ${{ contains(github.event.head_commit.message, '+next') && 'false' || 'true' }}

  test-terraform:
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      TF_WORKSPACE: dev
    outputs:
      no_change: ${{ steps.plan.outputs.no_change }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup terraform
        uses: ./.github/actions/install-terraform
        with:
          tf-api-token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        id: init
        run: |
          cd deployments/infra-data
          terraform init

      - name: Terraform Validate
        id: validate
        continue-on-error: true
        run: |
          cd deployments/infra-data
          terraform validate -no-color

      - name: Terraform Format
        id: fmt
        continue-on-error: true
        run: |
          cd deployments/infra-data
          terraform fmt -check

      - name: Terraform Plan (dev)
        id: plan
        continue-on-error: true
        run: |
          cd deployments/infra-data
          RC=0
          terraform plan -no-color || RC=$?

          if [[ $RC -eq 0 ]] ; then
           echo "no_change=true" >> $GITHUB_OUTPUT
          else
            if [[ $RC -eq 2 ]] ; then 
              echo "no_change=false" >> $GITHUB_OUTPUT
            else
              return $RC
            fi
          fi

      - name: Save plan in file
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        run: |
          echo "$PLAN" > terraform-plan-dev.log

      - name: Upload Plan (dev)
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-dev.log
          path: terraform-plan-dev.log

      - name: Publish Plan (dev)
        uses: actions/github-script@v7
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'thomasduchatelle:${{ github.ref_name }}'
            });
            
            if (prs.status !== 200 || prs.data.length == 0) {
              console.log("No open PR for this branch [${{ github.ref }}]");
              return
            }
            
            let summary = "";
            if ('${{ steps.plan.outputs.no_change }}' === 'true' ) {
              summary = " - no change"
            }
            
            const output = `
            * ${{ steps.fmt.outcome == 'success' && ':white_check_mark:' || ':x:' }} Formatting \`${{ steps.fmt.outcome }}\`
            * ${{ steps.init.outcome == 'success' && ':white_check_mark:' || ':x:' }} Initialisation  \`${{ steps.init.outcome }}\`
            * ${{ steps.validate.outcome == 'success' && ':white_check_mark:' || ':x:' }} Validation \`${{ steps.validate.outcome }}\`
            * ${{ steps.plan.outcome == 'success' && ':white_check_mark:' || ':x:' }} Plan \`${{ steps.plan.outcome }}\`
            
            ### Dev Plan
            
            <details><summary>Show Plan${summary}</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: prs.data[0].number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: contains(steps.*.outcome, 'failure')
        run: exit 1

  deploy-next:
    needs:
      - semver
      - test-terraform
      - test-build-web
    if: ${{ success() && contains(github.event.head_commit.message, '+next') }}
    uses: ./.github/workflows/lib-deploy.yml
    secrets: inherit
    with:
      target: next
      terraform-disabled: ${{ needs.test-terraform.outputs.no_change }}
