name: PR Terraform plan
on:
  pull_request:
    branches:
      - main
      - next
  workflow_call:
    inputs:
      issue-number:
        description: "Override the issue number on which the comment is posted"
        required: true
        type: string

jobs:
  live-cdk-plan:
    uses: ./.github/workflows/job-cdk-pr-plan.yml
    secrets: inherit
    with:
      issue-number: ${{ github.event_name == 'pull_request' && github.event.number || inputs.issue-number }}